/**
 * generated by Xtext
 */
package sc.ndt.editor.bmodes.validation;

import sc.ndt.editor.bmodes.validation.AbstractBmodesbmiValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class BmodesbmiValidator extends AbstractBmodesbmiValidator {
}
