/*
* generated by Xtext
*/
package sc.ndt.editor.bmodes;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BmodestspStandaloneSetup extends BmodestspStandaloneSetupGenerated{

	public static void doSetup() {
		new BmodestspStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

