/*
* generated by Xtext
*/
package sc.ndt.editor.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import sc.ndt.editor.services.TurbsimtbsGrammarAccess;

public class TurbsimtbsParser extends AbstractContentAssistParser {
	
	@Inject
	private TurbsimtbsGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected sc.ndt.editor.ui.contentassist.antlr.internal.InternalTurbsimtbsParser createParser() {
		sc.ndt.editor.ui.contentassist.antlr.internal.InternalTurbsimtbsParser result = new sc.ndt.editor.ui.contentassist.antlr.internal.InternalTurbsimtbsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelTurbsimtbsAccess().getAlternatives_57(), "rule__ModelTurbsimtbs__Alternatives_57");
					put(grammarAccess.getTBOOLAccess().getAlternatives(), "rule__TBOOL__Alternatives");
					put(grammarAccess.getTNUMAccess().getAlternatives(), "rule__TNUM__Alternatives");
					put(grammarAccess.getTNUMBERAccess().getAlternatives(), "rule__TNUMBER__Alternatives");
					put(grammarAccess.getTSEED1Access().getAlternatives(), "rule__TSEED1__Alternatives");
					put(grammarAccess.getTSEED2Access().getAlternatives(), "rule__TSEED2__Alternatives");
					put(grammarAccess.getSCTEventFileAccess().getValueAlternatives_1_0(), "rule__SCTEventFile__ValueAlternatives_1_0");
					put(grammarAccess.getModelTurbsimtbsAccess().getGroup(), "rule__ModelTurbsimtbs__Group__0");
					put(grammarAccess.getHeaderAccess().getGroup(), "rule__Header__Group__0");
					put(grammarAccess.getSectionAccess().getGroup(), "rule__Section__Group__0");
					put(grammarAccess.getNRandSeed1Access().getGroup(), "rule__NRandSeed1__Group__0");
					put(grammarAccess.getNRandSeed2Access().getGroup(), "rule__NRandSeed2__Group__0");
					put(grammarAccess.getBWrBHHTPAccess().getGroup(), "rule__BWrBHHTP__Group__0");
					put(grammarAccess.getBWrFHHTPAccess().getGroup(), "rule__BWrFHHTP__Group__0");
					put(grammarAccess.getBWrADHHAccess().getGroup(), "rule__BWrADHH__Group__0");
					put(grammarAccess.getBWrADFFAccess().getGroup(), "rule__BWrADFF__Group__0");
					put(grammarAccess.getBWrBLFFAccess().getGroup(), "rule__BWrBLFF__Group__0");
					put(grammarAccess.getBWrADTWRAccess().getGroup(), "rule__BWrADTWR__Group__0");
					put(grammarAccess.getBWrFMTFFAccess().getGroup(), "rule__BWrFMTFF__Group__0");
					put(grammarAccess.getBWrACTAccess().getGroup(), "rule__BWrACT__Group__0");
					put(grammarAccess.getBClockwiseAccess().getGroup(), "rule__BClockwise__Group__0");
					put(grammarAccess.getIScaleIECAccess().getGroup(), "rule__IScaleIEC__Group__0");
					put(grammarAccess.getINumGrid_ZAccess().getGroup(), "rule__INumGrid_Z__Group__0");
					put(grammarAccess.getINumGrid_YAccess().getGroup(), "rule__INumGrid_Y__Group__0");
					put(grammarAccess.getNTimeStepAccess().getGroup(), "rule__NTimeStep__Group__0");
					put(grammarAccess.getNAnalysisTimeAccess().getGroup(), "rule__NAnalysisTime__Group__0");
					put(grammarAccess.getNUsableTimeAccess().getGroup(), "rule__NUsableTime__Group__0");
					put(grammarAccess.getNHubHtAccess().getGroup(), "rule__NHubHt__Group__0");
					put(grammarAccess.getNGridHeightAccess().getGroup(), "rule__NGridHeight__Group__0");
					put(grammarAccess.getNGridWidthAccess().getGroup(), "rule__NGridWidth__Group__0");
					put(grammarAccess.getNVFlowAngAccess().getGroup(), "rule__NVFlowAng__Group__0");
					put(grammarAccess.getNHFlowAngAccess().getGroup(), "rule__NHFlowAng__Group__0");
					put(grammarAccess.getSTurbModelAccess().getGroup(), "rule__STurbModel__Group__0");
					put(grammarAccess.getSIECstandardAccess().getGroup(), "rule__SIECstandard__Group__0");
					put(grammarAccess.getSIECturbcAccess().getGroup(), "rule__SIECturbc__Group__0");
					put(grammarAccess.getSIEC_WindTypeAccess().getGroup(), "rule__SIEC_WindType__Group__0");
					put(grammarAccess.getSETMcAccess().getGroup(), "rule__SETMc__Group__0");
					put(grammarAccess.getSWindProfileTypeAccess().getGroup(), "rule__SWindProfileType__Group__0");
					put(grammarAccess.getNRefHtAccess().getGroup(), "rule__NRefHt__Group__0");
					put(grammarAccess.getNUrefAccess().getGroup(), "rule__NUref__Group__0");
					put(grammarAccess.getNZJetMaxAccess().getGroup(), "rule__NZJetMax__Group__0");
					put(grammarAccess.getNPLExpAccess().getGroup(), "rule__NPLExp__Group__0");
					put(grammarAccess.getNZ0Access().getGroup(), "rule__NZ0__Group__0");
					put(grammarAccess.getNLocationAccess().getGroup(), "rule__NLocation__Group__0");
					put(grammarAccess.getNRICH_NOAccess().getGroup(), "rule__NRICH_NO__Group__0");
					put(grammarAccess.getNUStarAccess().getGroup(), "rule__NUStar__Group__0");
					put(grammarAccess.getNZIAccess().getGroup(), "rule__NZI__Group__0");
					put(grammarAccess.getNPC_UWAccess().getGroup(), "rule__NPC_UW__Group__0");
					put(grammarAccess.getNPC_UVAccess().getGroup(), "rule__NPC_UV__Group__0");
					put(grammarAccess.getNPC_VWAccess().getGroup(), "rule__NPC_VW__Group__0");
					put(grammarAccess.getNIncDec1Access().getGroup(), "rule__NIncDec1__Group__0");
					put(grammarAccess.getNIncDec2Access().getGroup(), "rule__NIncDec2__Group__0");
					put(grammarAccess.getNIncDec3Access().getGroup(), "rule__NIncDec3__Group__0");
					put(grammarAccess.getNCohExpAccess().getGroup(), "rule__NCohExp__Group__0");
					put(grammarAccess.getSCTEventPathAccess().getGroup(), "rule__SCTEventPath__Group__0");
					put(grammarAccess.getSCTEventFileAccess().getGroup(), "rule__SCTEventFile__Group__0");
					put(grammarAccess.getBRandomizeAccess().getGroup(), "rule__BRandomize__Group__0");
					put(grammarAccess.getNDistSclAccess().getGroup(), "rule__NDistScl__Group__0");
					put(grammarAccess.getNCTLyAccess().getGroup(), "rule__NCTLy__Group__0");
					put(grammarAccess.getNCTLzAccess().getGroup(), "rule__NCTLz__Group__0");
					put(grammarAccess.getNCTStartTimeAccess().getGroup(), "rule__NCTStartTime__Group__0");
					put(grammarAccess.getModelTurbsimtbsAccess().getHeadAssignment_0(), "rule__ModelTurbsimtbs__HeadAssignment_0");
					put(grammarAccess.getModelTurbsimtbsAccess().getSectionsAssignment_1(), "rule__ModelTurbsimtbs__SectionsAssignment_1");
					put(grammarAccess.getModelTurbsimtbsAccess().getRandSeed1Assignment_2(), "rule__ModelTurbsimtbs__RandSeed1Assignment_2");
					put(grammarAccess.getModelTurbsimtbsAccess().getRandSeed2Assignment_3(), "rule__ModelTurbsimtbs__RandSeed2Assignment_3");
					put(grammarAccess.getModelTurbsimtbsAccess().getWrBHHTPAssignment_4(), "rule__ModelTurbsimtbs__WrBHHTPAssignment_4");
					put(grammarAccess.getModelTurbsimtbsAccess().getWrFHHTPAssignment_5(), "rule__ModelTurbsimtbs__WrFHHTPAssignment_5");
					put(grammarAccess.getModelTurbsimtbsAccess().getWrADHHAssignment_6(), "rule__ModelTurbsimtbs__WrADHHAssignment_6");
					put(grammarAccess.getModelTurbsimtbsAccess().getWrADFFAssignment_7(), "rule__ModelTurbsimtbs__WrADFFAssignment_7");
					put(grammarAccess.getModelTurbsimtbsAccess().getWrBLFFAssignment_8(), "rule__ModelTurbsimtbs__WrBLFFAssignment_8");
					put(grammarAccess.getModelTurbsimtbsAccess().getWrADTWRAssignment_9(), "rule__ModelTurbsimtbs__WrADTWRAssignment_9");
					put(grammarAccess.getModelTurbsimtbsAccess().getWrFMTFFAssignment_10(), "rule__ModelTurbsimtbs__WrFMTFFAssignment_10");
					put(grammarAccess.getModelTurbsimtbsAccess().getWrACTAssignment_11(), "rule__ModelTurbsimtbs__WrACTAssignment_11");
					put(grammarAccess.getModelTurbsimtbsAccess().getClockwiseAssignment_12(), "rule__ModelTurbsimtbs__ClockwiseAssignment_12");
					put(grammarAccess.getModelTurbsimtbsAccess().getScaleIECAssignment_13(), "rule__ModelTurbsimtbs__ScaleIECAssignment_13");
					put(grammarAccess.getModelTurbsimtbsAccess().getSectionsAssignment_14(), "rule__ModelTurbsimtbs__SectionsAssignment_14");
					put(grammarAccess.getModelTurbsimtbsAccess().getNumGrid_ZAssignment_15(), "rule__ModelTurbsimtbs__NumGrid_ZAssignment_15");
					put(grammarAccess.getModelTurbsimtbsAccess().getNumGrid_YAssignment_16(), "rule__ModelTurbsimtbs__NumGrid_YAssignment_16");
					put(grammarAccess.getModelTurbsimtbsAccess().getTimeStepAssignment_17(), "rule__ModelTurbsimtbs__TimeStepAssignment_17");
					put(grammarAccess.getModelTurbsimtbsAccess().getAnalysisTimeAssignment_18(), "rule__ModelTurbsimtbs__AnalysisTimeAssignment_18");
					put(grammarAccess.getModelTurbsimtbsAccess().getUsableTimeAssignment_19(), "rule__ModelTurbsimtbs__UsableTimeAssignment_19");
					put(grammarAccess.getModelTurbsimtbsAccess().getHubHtAssignment_20(), "rule__ModelTurbsimtbs__HubHtAssignment_20");
					put(grammarAccess.getModelTurbsimtbsAccess().getGridHeightAssignment_21(), "rule__ModelTurbsimtbs__GridHeightAssignment_21");
					put(grammarAccess.getModelTurbsimtbsAccess().getGridWidthAssignment_22(), "rule__ModelTurbsimtbs__GridWidthAssignment_22");
					put(grammarAccess.getModelTurbsimtbsAccess().getVFlowAngAssignment_23(), "rule__ModelTurbsimtbs__VFlowAngAssignment_23");
					put(grammarAccess.getModelTurbsimtbsAccess().getHFlowAngAssignment_24(), "rule__ModelTurbsimtbs__HFlowAngAssignment_24");
					put(grammarAccess.getModelTurbsimtbsAccess().getSectionsAssignment_25(), "rule__ModelTurbsimtbs__SectionsAssignment_25");
					put(grammarAccess.getModelTurbsimtbsAccess().getTurbModelAssignment_26(), "rule__ModelTurbsimtbs__TurbModelAssignment_26");
					put(grammarAccess.getModelTurbsimtbsAccess().getIECstandardAssignment_27(), "rule__ModelTurbsimtbs__IECstandardAssignment_27");
					put(grammarAccess.getModelTurbsimtbsAccess().getIECturbcAssignment_28(), "rule__ModelTurbsimtbs__IECturbcAssignment_28");
					put(grammarAccess.getModelTurbsimtbsAccess().getIEC_WindTypeAssignment_29(), "rule__ModelTurbsimtbs__IEC_WindTypeAssignment_29");
					put(grammarAccess.getModelTurbsimtbsAccess().getETMcAssignment_30(), "rule__ModelTurbsimtbs__ETMcAssignment_30");
					put(grammarAccess.getModelTurbsimtbsAccess().getWindProfileTypeAssignment_31(), "rule__ModelTurbsimtbs__WindProfileTypeAssignment_31");
					put(grammarAccess.getModelTurbsimtbsAccess().getRefHtAssignment_32(), "rule__ModelTurbsimtbs__RefHtAssignment_32");
					put(grammarAccess.getModelTurbsimtbsAccess().getUrefAssignment_33(), "rule__ModelTurbsimtbs__UrefAssignment_33");
					put(grammarAccess.getModelTurbsimtbsAccess().getZJetMaxAssignment_34(), "rule__ModelTurbsimtbs__ZJetMaxAssignment_34");
					put(grammarAccess.getModelTurbsimtbsAccess().getPLExpAssignment_35(), "rule__ModelTurbsimtbs__PLExpAssignment_35");
					put(grammarAccess.getModelTurbsimtbsAccess().getZ0Assignment_36(), "rule__ModelTurbsimtbs__Z0Assignment_36");
					put(grammarAccess.getModelTurbsimtbsAccess().getSectionsAssignment_37(), "rule__ModelTurbsimtbs__SectionsAssignment_37");
					put(grammarAccess.getModelTurbsimtbsAccess().getLocationAssignment_38(), "rule__ModelTurbsimtbs__LocationAssignment_38");
					put(grammarAccess.getModelTurbsimtbsAccess().getRICH_NOAssignment_39(), "rule__ModelTurbsimtbs__RICH_NOAssignment_39");
					put(grammarAccess.getModelTurbsimtbsAccess().getUStarAssignment_40(), "rule__ModelTurbsimtbs__UStarAssignment_40");
					put(grammarAccess.getModelTurbsimtbsAccess().getZIAssignment_41(), "rule__ModelTurbsimtbs__ZIAssignment_41");
					put(grammarAccess.getModelTurbsimtbsAccess().getPC_UWAssignment_42(), "rule__ModelTurbsimtbs__PC_UWAssignment_42");
					put(grammarAccess.getModelTurbsimtbsAccess().getPC_UVAssignment_43(), "rule__ModelTurbsimtbs__PC_UVAssignment_43");
					put(grammarAccess.getModelTurbsimtbsAccess().getPC_VWAssignment_44(), "rule__ModelTurbsimtbs__PC_VWAssignment_44");
					put(grammarAccess.getModelTurbsimtbsAccess().getIncDec1Assignment_45(), "rule__ModelTurbsimtbs__IncDec1Assignment_45");
					put(grammarAccess.getModelTurbsimtbsAccess().getIncDec2Assignment_46(), "rule__ModelTurbsimtbs__IncDec2Assignment_46");
					put(grammarAccess.getModelTurbsimtbsAccess().getIncDec3Assignment_47(), "rule__ModelTurbsimtbs__IncDec3Assignment_47");
					put(grammarAccess.getModelTurbsimtbsAccess().getCohExpAssignment_48(), "rule__ModelTurbsimtbs__CohExpAssignment_48");
					put(grammarAccess.getModelTurbsimtbsAccess().getSectionsAssignment_49(), "rule__ModelTurbsimtbs__SectionsAssignment_49");
					put(grammarAccess.getModelTurbsimtbsAccess().getCTEventPathAssignment_50(), "rule__ModelTurbsimtbs__CTEventPathAssignment_50");
					put(grammarAccess.getModelTurbsimtbsAccess().getCTEventFileAssignment_51(), "rule__ModelTurbsimtbs__CTEventFileAssignment_51");
					put(grammarAccess.getModelTurbsimtbsAccess().getRandomizeAssignment_52(), "rule__ModelTurbsimtbs__RandomizeAssignment_52");
					put(grammarAccess.getModelTurbsimtbsAccess().getDistSclAssignment_53(), "rule__ModelTurbsimtbs__DistSclAssignment_53");
					put(grammarAccess.getModelTurbsimtbsAccess().getCTLyAssignment_54(), "rule__ModelTurbsimtbs__CTLyAssignment_54");
					put(grammarAccess.getModelTurbsimtbsAccess().getCTLzAssignment_55(), "rule__ModelTurbsimtbs__CTLzAssignment_55");
					put(grammarAccess.getModelTurbsimtbsAccess().getCTStartTimeAssignment_56(), "rule__ModelTurbsimtbs__CTStartTimeAssignment_56");
					put(grammarAccess.getHeaderAccess().getRowsAssignment_0(), "rule__Header__RowsAssignment_0");
					put(grammarAccess.getSectionAccess().getNameAssignment_2(), "rule__Section__NameAssignment_2");
					put(grammarAccess.getNRandSeed1Access().getValueAssignment_1(), "rule__NRandSeed1__ValueAssignment_1");
					put(grammarAccess.getNRandSeed1Access().getNameAssignment_3(), "rule__NRandSeed1__NameAssignment_3");
					put(grammarAccess.getNRandSeed2Access().getValueAssignment_1(), "rule__NRandSeed2__ValueAssignment_1");
					put(grammarAccess.getNRandSeed2Access().getNameAssignment_3(), "rule__NRandSeed2__NameAssignment_3");
					put(grammarAccess.getBWrBHHTPAccess().getValueAssignment_1(), "rule__BWrBHHTP__ValueAssignment_1");
					put(grammarAccess.getBWrBHHTPAccess().getNameAssignment_3(), "rule__BWrBHHTP__NameAssignment_3");
					put(grammarAccess.getBWrFHHTPAccess().getValueAssignment_1(), "rule__BWrFHHTP__ValueAssignment_1");
					put(grammarAccess.getBWrFHHTPAccess().getNameAssignment_3(), "rule__BWrFHHTP__NameAssignment_3");
					put(grammarAccess.getBWrADHHAccess().getValueAssignment_1(), "rule__BWrADHH__ValueAssignment_1");
					put(grammarAccess.getBWrADHHAccess().getNameAssignment_3(), "rule__BWrADHH__NameAssignment_3");
					put(grammarAccess.getBWrADFFAccess().getValueAssignment_1(), "rule__BWrADFF__ValueAssignment_1");
					put(grammarAccess.getBWrADFFAccess().getNameAssignment_3(), "rule__BWrADFF__NameAssignment_3");
					put(grammarAccess.getBWrBLFFAccess().getValueAssignment_1(), "rule__BWrBLFF__ValueAssignment_1");
					put(grammarAccess.getBWrBLFFAccess().getNameAssignment_3(), "rule__BWrBLFF__NameAssignment_3");
					put(grammarAccess.getBWrADTWRAccess().getValueAssignment_1(), "rule__BWrADTWR__ValueAssignment_1");
					put(grammarAccess.getBWrADTWRAccess().getNameAssignment_3(), "rule__BWrADTWR__NameAssignment_3");
					put(grammarAccess.getBWrFMTFFAccess().getValueAssignment_1(), "rule__BWrFMTFF__ValueAssignment_1");
					put(grammarAccess.getBWrFMTFFAccess().getNameAssignment_3(), "rule__BWrFMTFF__NameAssignment_3");
					put(grammarAccess.getBWrACTAccess().getValueAssignment_1(), "rule__BWrACT__ValueAssignment_1");
					put(grammarAccess.getBWrACTAccess().getNameAssignment_3(), "rule__BWrACT__NameAssignment_3");
					put(grammarAccess.getBClockwiseAccess().getValueAssignment_1(), "rule__BClockwise__ValueAssignment_1");
					put(grammarAccess.getBClockwiseAccess().getNameAssignment_3(), "rule__BClockwise__NameAssignment_3");
					put(grammarAccess.getIScaleIECAccess().getValueAssignment_1(), "rule__IScaleIEC__ValueAssignment_1");
					put(grammarAccess.getIScaleIECAccess().getNameAssignment_3(), "rule__IScaleIEC__NameAssignment_3");
					put(grammarAccess.getINumGrid_ZAccess().getValueAssignment_1(), "rule__INumGrid_Z__ValueAssignment_1");
					put(grammarAccess.getINumGrid_ZAccess().getNameAssignment_3(), "rule__INumGrid_Z__NameAssignment_3");
					put(grammarAccess.getINumGrid_YAccess().getValueAssignment_1(), "rule__INumGrid_Y__ValueAssignment_1");
					put(grammarAccess.getINumGrid_YAccess().getNameAssignment_3(), "rule__INumGrid_Y__NameAssignment_3");
					put(grammarAccess.getNTimeStepAccess().getValueAssignment_1(), "rule__NTimeStep__ValueAssignment_1");
					put(grammarAccess.getNTimeStepAccess().getNameAssignment_3(), "rule__NTimeStep__NameAssignment_3");
					put(grammarAccess.getNAnalysisTimeAccess().getValueAssignment_1(), "rule__NAnalysisTime__ValueAssignment_1");
					put(grammarAccess.getNAnalysisTimeAccess().getNameAssignment_3(), "rule__NAnalysisTime__NameAssignment_3");
					put(grammarAccess.getNUsableTimeAccess().getValueAssignment_1(), "rule__NUsableTime__ValueAssignment_1");
					put(grammarAccess.getNUsableTimeAccess().getNameAssignment_3(), "rule__NUsableTime__NameAssignment_3");
					put(grammarAccess.getNHubHtAccess().getValueAssignment_1(), "rule__NHubHt__ValueAssignment_1");
					put(grammarAccess.getNHubHtAccess().getNameAssignment_3(), "rule__NHubHt__NameAssignment_3");
					put(grammarAccess.getNGridHeightAccess().getValueAssignment_1(), "rule__NGridHeight__ValueAssignment_1");
					put(grammarAccess.getNGridHeightAccess().getNameAssignment_3(), "rule__NGridHeight__NameAssignment_3");
					put(grammarAccess.getNGridWidthAccess().getValueAssignment_1(), "rule__NGridWidth__ValueAssignment_1");
					put(grammarAccess.getNGridWidthAccess().getNameAssignment_3(), "rule__NGridWidth__NameAssignment_3");
					put(grammarAccess.getNVFlowAngAccess().getValueAssignment_1(), "rule__NVFlowAng__ValueAssignment_1");
					put(grammarAccess.getNVFlowAngAccess().getNameAssignment_3(), "rule__NVFlowAng__NameAssignment_3");
					put(grammarAccess.getNHFlowAngAccess().getValueAssignment_1(), "rule__NHFlowAng__ValueAssignment_1");
					put(grammarAccess.getNHFlowAngAccess().getNameAssignment_3(), "rule__NHFlowAng__NameAssignment_3");
					put(grammarAccess.getSTurbModelAccess().getValueAssignment_1(), "rule__STurbModel__ValueAssignment_1");
					put(grammarAccess.getSTurbModelAccess().getNameAssignment_3(), "rule__STurbModel__NameAssignment_3");
					put(grammarAccess.getSIECstandardAccess().getValueAssignment_1(), "rule__SIECstandard__ValueAssignment_1");
					put(grammarAccess.getSIECstandardAccess().getNameAssignment_3(), "rule__SIECstandard__NameAssignment_3");
					put(grammarAccess.getSIECturbcAccess().getValueAssignment_1(), "rule__SIECturbc__ValueAssignment_1");
					put(grammarAccess.getSIECturbcAccess().getNameAssignment_3(), "rule__SIECturbc__NameAssignment_3");
					put(grammarAccess.getSIEC_WindTypeAccess().getValueAssignment_1(), "rule__SIEC_WindType__ValueAssignment_1");
					put(grammarAccess.getSIEC_WindTypeAccess().getNameAssignment_3(), "rule__SIEC_WindType__NameAssignment_3");
					put(grammarAccess.getSETMcAccess().getValueAssignment_1(), "rule__SETMc__ValueAssignment_1");
					put(grammarAccess.getSETMcAccess().getNameAssignment_3(), "rule__SETMc__NameAssignment_3");
					put(grammarAccess.getSWindProfileTypeAccess().getValueAssignment_1(), "rule__SWindProfileType__ValueAssignment_1");
					put(grammarAccess.getSWindProfileTypeAccess().getNameAssignment_3(), "rule__SWindProfileType__NameAssignment_3");
					put(grammarAccess.getNRefHtAccess().getValueAssignment_1(), "rule__NRefHt__ValueAssignment_1");
					put(grammarAccess.getNRefHtAccess().getNameAssignment_3(), "rule__NRefHt__NameAssignment_3");
					put(grammarAccess.getNUrefAccess().getValueAssignment_1(), "rule__NUref__ValueAssignment_1");
					put(grammarAccess.getNUrefAccess().getNameAssignment_3(), "rule__NUref__NameAssignment_3");
					put(grammarAccess.getNZJetMaxAccess().getValueAssignment_1(), "rule__NZJetMax__ValueAssignment_1");
					put(grammarAccess.getNZJetMaxAccess().getNameAssignment_3(), "rule__NZJetMax__NameAssignment_3");
					put(grammarAccess.getNPLExpAccess().getValueAssignment_1(), "rule__NPLExp__ValueAssignment_1");
					put(grammarAccess.getNPLExpAccess().getNameAssignment_3(), "rule__NPLExp__NameAssignment_3");
					put(grammarAccess.getNZ0Access().getValueAssignment_1(), "rule__NZ0__ValueAssignment_1");
					put(grammarAccess.getNZ0Access().getNameAssignment_3(), "rule__NZ0__NameAssignment_3");
					put(grammarAccess.getNLocationAccess().getValueAssignment_1(), "rule__NLocation__ValueAssignment_1");
					put(grammarAccess.getNLocationAccess().getNameAssignment_3(), "rule__NLocation__NameAssignment_3");
					put(grammarAccess.getNRICH_NOAccess().getValueAssignment_1(), "rule__NRICH_NO__ValueAssignment_1");
					put(grammarAccess.getNRICH_NOAccess().getNameAssignment_3(), "rule__NRICH_NO__NameAssignment_3");
					put(grammarAccess.getNUStarAccess().getValueAssignment_1(), "rule__NUStar__ValueAssignment_1");
					put(grammarAccess.getNUStarAccess().getNameAssignment_3(), "rule__NUStar__NameAssignment_3");
					put(grammarAccess.getNZIAccess().getValueAssignment_1(), "rule__NZI__ValueAssignment_1");
					put(grammarAccess.getNZIAccess().getNameAssignment_3(), "rule__NZI__NameAssignment_3");
					put(grammarAccess.getNPC_UWAccess().getValueAssignment_1(), "rule__NPC_UW__ValueAssignment_1");
					put(grammarAccess.getNPC_UWAccess().getNameAssignment_3(), "rule__NPC_UW__NameAssignment_3");
					put(grammarAccess.getNPC_UVAccess().getValueAssignment_1(), "rule__NPC_UV__ValueAssignment_1");
					put(grammarAccess.getNPC_UVAccess().getNameAssignment_3(), "rule__NPC_UV__NameAssignment_3");
					put(grammarAccess.getNPC_VWAccess().getValueAssignment_1(), "rule__NPC_VW__ValueAssignment_1");
					put(grammarAccess.getNPC_VWAccess().getNameAssignment_3(), "rule__NPC_VW__NameAssignment_3");
					put(grammarAccess.getNIncDec1Access().getValueAssignment_1(), "rule__NIncDec1__ValueAssignment_1");
					put(grammarAccess.getNIncDec1Access().getNameAssignment_3(), "rule__NIncDec1__NameAssignment_3");
					put(grammarAccess.getNIncDec2Access().getValueAssignment_1(), "rule__NIncDec2__ValueAssignment_1");
					put(grammarAccess.getNIncDec2Access().getNameAssignment_3(), "rule__NIncDec2__NameAssignment_3");
					put(grammarAccess.getNIncDec3Access().getValueAssignment_1(), "rule__NIncDec3__ValueAssignment_1");
					put(grammarAccess.getNIncDec3Access().getNameAssignment_3(), "rule__NIncDec3__NameAssignment_3");
					put(grammarAccess.getNCohExpAccess().getValueAssignment_1(), "rule__NCohExp__ValueAssignment_1");
					put(grammarAccess.getNCohExpAccess().getNameAssignment_3(), "rule__NCohExp__NameAssignment_3");
					put(grammarAccess.getSCTEventPathAccess().getValueAssignment_1(), "rule__SCTEventPath__ValueAssignment_1");
					put(grammarAccess.getSCTEventPathAccess().getNameAssignment_3(), "rule__SCTEventPath__NameAssignment_3");
					put(grammarAccess.getSCTEventFileAccess().getValueAssignment_1(), "rule__SCTEventFile__ValueAssignment_1");
					put(grammarAccess.getSCTEventFileAccess().getNameAssignment_3(), "rule__SCTEventFile__NameAssignment_3");
					put(grammarAccess.getBRandomizeAccess().getValueAssignment_1(), "rule__BRandomize__ValueAssignment_1");
					put(grammarAccess.getBRandomizeAccess().getNameAssignment_3(), "rule__BRandomize__NameAssignment_3");
					put(grammarAccess.getNDistSclAccess().getValueAssignment_1(), "rule__NDistScl__ValueAssignment_1");
					put(grammarAccess.getNDistSclAccess().getNameAssignment_3(), "rule__NDistScl__NameAssignment_3");
					put(grammarAccess.getNCTLyAccess().getValueAssignment_1(), "rule__NCTLy__ValueAssignment_1");
					put(grammarAccess.getNCTLyAccess().getNameAssignment_3(), "rule__NCTLy__NameAssignment_3");
					put(grammarAccess.getNCTLzAccess().getValueAssignment_1(), "rule__NCTLz__ValueAssignment_1");
					put(grammarAccess.getNCTLzAccess().getNameAssignment_3(), "rule__NCTLz__NameAssignment_3");
					put(grammarAccess.getNCTStartTimeAccess().getValueAssignment_1(), "rule__NCTStartTime__ValueAssignment_1");
					put(grammarAccess.getNCTStartTimeAccess().getNameAssignment_3(), "rule__NCTStartTime__NameAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			sc.ndt.editor.ui.contentassist.antlr.internal.InternalTurbsimtbsParser typedParser = (sc.ndt.editor.ui.contentassist.antlr.internal.InternalTurbsimtbsParser) parser;
			typedParser.entryRuleModelTurbsimtbs();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] {  };
	}
	
	public TurbsimtbsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TurbsimtbsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
