/*
* generated by Xtext
*/
package sc.ndt.editor.iecwind.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sc.ndt.editor.iecwind.services.IecwindiecGrammarAccess;

public class IecwindiecParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private IecwindiecGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected sc.ndt.editor.iecwind.parser.antlr.internal.InternalIecwindiecParser createParser(XtextTokenStream stream) {
		return new sc.ndt.editor.iecwind.parser.antlr.internal.InternalIecwindiecParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ModelIecwindiec";
	}
	
	public IecwindiecGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(IecwindiecGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
