/*
 * generated by Xtext
 */
package sc.ndt.editor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BmodesoutRuntimeModule extends sc.ndt.editor.AbstractBmodesoutRuntimeModule {

}
