/*
* generated by Xtext
*/
package sc.ndt.editor.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sc.ndt.editor.services.TurbsimtbsGrammarAccess;

public class TurbsimtbsParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TurbsimtbsGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected sc.ndt.editor.parser.antlr.internal.InternalTurbsimtbsParser createParser(XtextTokenStream stream) {
		return new sc.ndt.editor.parser.antlr.internal.InternalTurbsimtbsParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public TurbsimtbsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TurbsimtbsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
