/*
* generated by Xtext
*/
package sc.ndt.editor.fast.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sc.ndt.editor.fast.services.FastbldGrammarAccess;

public class FastbldParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FastbldGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected sc.ndt.editor.fast.parser.antlr.internal.InternalFastbldParser createParser(XtextTokenStream stream) {
		return new sc.ndt.editor.fast.parser.antlr.internal.InternalFastbldParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ModelFastbld";
	}
	
	public FastbldGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FastbldGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
