/*
 * generated by Xtext
 */
package sc.ndt.editor.fast.ui.contentassist

import sc.ndt.editor.fast.ui.contentassist.AbstractFastbldProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FastbldProposalProvider extends AbstractFastbldProposalProvider {
}
