/*
 * generated by Xtext
 */
package sc.ndt.editor.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import sc.ndt.editor.ui.internal.BmodesbmiActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BmodesbmiExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BmodesbmiActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BmodesbmiActivator.getInstance().getInjector(BmodesbmiActivator.SC_NDT_EDITOR_BMODESBMI);
	}
	
}
