/**
 * generated by Xtext
 */
package sc.ndt.editor.fast.validation;

import sc.ndt.editor.fast.validation.AbstractFastadnValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class FastadnValidator extends AbstractFastadnValidator {
}
