/*
* generated by Xtext
*/
package sc.ndt.editor.bmodes;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BmodesoutStandaloneSetup extends BmodesoutStandaloneSetupGenerated{

	public static void doSetup() {
		new BmodesoutStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

