/*
* generated by Xtext
*/
package sc.ndt.editor.iecwind;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class IecwindiecStandaloneSetup extends IecwindiecStandaloneSetupGenerated{

	public static void doSetup() {
		new IecwindiecStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

