/*
* generated by Xtext
*/
package sc.ndt.editor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BmodesoutAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("sc/ndt/editor/parser/antlr/internal/InternalBmodesout.tokens");
	}
}
