/*
* generated by Xtext
*/
package sc.ndt.editor.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sc.ndt.editor.services.BmodesoutGrammarAccess;

public class BmodesoutParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BmodesoutGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens();
	}
	
	@Override
	protected sc.ndt.editor.parser.antlr.internal.InternalBmodesoutParser createParser(XtextTokenStream stream) {
		return new sc.ndt.editor.parser.antlr.internal.InternalBmodesoutParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ModelBmodesout";
	}
	
	public BmodesoutGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BmodesoutGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
