/*
* generated by Xtext
*/
package sc.ndt.editor.bmodes.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import sc.ndt.editor.bmodes.services.BmodesbmiGrammarAccess;

public class BmodesbmiParser extends AbstractContentAssistParser {
	
	@Inject
	private BmodesbmiGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected sc.ndt.editor.bmodes.ui.contentassist.antlr.internal.InternalBmodesbmiParser createParser() {
		sc.ndt.editor.bmodes.ui.contentassist.antlr.internal.InternalBmodesbmiParser result = new sc.ndt.editor.bmodes.ui.contentassist.antlr.internal.InternalBmodesbmiParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelBmodesbmiAccess().getAlternatives_55(), "rule__ModelBmodesbmi__Alternatives_55");
					put(grammarAccess.getTNUMBERAccess().getAlternatives(), "rule__TNUMBER__Alternatives");
					put(grammarAccess.getTBOOLAccess().getAlternatives(), "rule__TBOOL__Alternatives");
					put(grammarAccess.getModelBmodesbmiAccess().getGroup(), "rule__ModelBmodesbmi__Group__0");
					put(grammarAccess.getHeaderAccess().getGroup(), "rule__Header__Group__0");
					put(grammarAccess.getSectionAccess().getGroup(), "rule__Section__Group__0");
					put(grammarAccess.getBEchoAccess().getGroup(), "rule__BEcho__Group__0");
					put(grammarAccess.getIBeamTypeAccess().getGroup(), "rule__IBeamType__Group__0");
					put(grammarAccess.getNRotRpmAccess().getGroup(), "rule__NRotRpm__Group__0");
					put(grammarAccess.getNRpmMultAccess().getGroup(), "rule__NRpmMult__Group__0");
					put(grammarAccess.getNRadiusAccess().getGroup(), "rule__NRadius__Group__0");
					put(grammarAccess.getNHubRadAccess().getGroup(), "rule__NHubRad__Group__0");
					put(grammarAccess.getNPreconeAccess().getGroup(), "rule__NPrecone__Group__0");
					put(grammarAccess.getNBlThpAccess().getGroup(), "rule__NBlThp__Group__0");
					put(grammarAccess.getIHubConnAccess().getGroup(), "rule__IHubConn__Group__0");
					put(grammarAccess.getIModePrAccess().getGroup(), "rule__IModePr__Group__0");
					put(grammarAccess.getBTabDelimAccess().getGroup(), "rule__BTabDelim__Group__0");
					put(grammarAccess.getBMidNodeTwAccess().getGroup(), "rule__BMidNodeTw__Group__0");
					put(grammarAccess.getNTipMassAccess().getGroup(), "rule__NTipMass__Group__0");
					put(grammarAccess.getNCmLocAccess().getGroup(), "rule__NCmLoc__Group__0");
					put(grammarAccess.getNCmAxialAccess().getGroup(), "rule__NCmAxial__Group__0");
					put(grammarAccess.getNIxxTipAccess().getGroup(), "rule__NIxxTip__Group__0");
					put(grammarAccess.getNIyyTipAccess().getGroup(), "rule__NIyyTip__Group__0");
					put(grammarAccess.getNIzzTipAccess().getGroup(), "rule__NIzzTip__Group__0");
					put(grammarAccess.getNIxyTipAccess().getGroup(), "rule__NIxyTip__Group__0");
					put(grammarAccess.getNIzxTipAccess().getGroup(), "rule__NIzxTip__Group__0");
					put(grammarAccess.getNIyzTipAccess().getGroup(), "rule__NIyzTip__Group__0");
					put(grammarAccess.getIIdMatAccess().getGroup(), "rule__IIdMat__Group__0");
					put(grammarAccess.getISecFileAccess().getGroup(), "rule__ISecFile__Group__0");
					put(grammarAccess.getNSecMasMultAccess().getGroup(), "rule__NSecMasMult__Group__0");
					put(grammarAccess.getNFlpInrMultAccess().getGroup(), "rule__NFlpInrMult__Group__0");
					put(grammarAccess.getNLagInrMultAccess().getGroup(), "rule__NLagInrMult__Group__0");
					put(grammarAccess.getNFlpstfMultAccess().getGroup(), "rule__NFlpstfMult__Group__0");
					put(grammarAccess.getNEdgStfMultAccess().getGroup(), "rule__NEdgStfMult__Group__0");
					put(grammarAccess.getNTorStfMultAccess().getGroup(), "rule__NTorStfMult__Group__0");
					put(grammarAccess.getNAxiStfMultAccess().getGroup(), "rule__NAxiStfMult__Group__0");
					put(grammarAccess.getNCgOffsMultAccess().getGroup(), "rule__NCgOffsMult__Group__0");
					put(grammarAccess.getNScOffsMultAccess().getGroup(), "rule__NScOffsMult__Group__0");
					put(grammarAccess.getNTcOffsMultAccess().getGroup(), "rule__NTcOffsMult__Group__0");
					put(grammarAccess.getINSeltAccess().getGroup(), "rule__INSelt__Group__0");
					put(grammarAccess.getAElLocAccess().getGroup(), "rule__AElLoc__Group__0");
					put(grammarAccess.getAElLocAccess().getGroup_1(), "rule__AElLoc__Group_1__0");
					put(grammarAccess.getITwrSupportAccess().getGroup(), "rule__ITwrSupport__Group__0");
					put(grammarAccess.getITwrAttachAccess().getGroup(), "rule__ITwrAttach__Group__0");
					put(grammarAccess.getATwrWiresAccess().getGroup(), "rule__ATwrWires__Group__0");
					put(grammarAccess.getATwrWiresAccess().getGroup_1(), "rule__ATwrWires__Group_1__0");
					put(grammarAccess.getANodeAttachAccess().getGroup(), "rule__ANodeAttach__Group__0");
					put(grammarAccess.getANodeAttachAccess().getGroup_1(), "rule__ANodeAttach__Group_1__0");
					put(grammarAccess.getAWireStiffAccess().getGroup(), "rule__AWireStiff__Group__0");
					put(grammarAccess.getAWireStiffAccess().getGroup_1(), "rule__AWireStiff__Group_1__0");
					put(grammarAccess.getAWireAngleAccess().getGroup(), "rule__AWireAngle__Group__0");
					put(grammarAccess.getAWireAngleAccess().getGroup_1(), "rule__AWireAngle__Group_1__0");
					put(grammarAccess.getModelBmodesbmiAccess().getHeadAssignment_0(), "rule__ModelBmodesbmi__HeadAssignment_0");
					put(grammarAccess.getModelBmodesbmiAccess().getSecAssignment_1(), "rule__ModelBmodesbmi__SecAssignment_1");
					put(grammarAccess.getModelBmodesbmiAccess().getEchoAssignment_2(), "rule__ModelBmodesbmi__EchoAssignment_2");
					put(grammarAccess.getModelBmodesbmiAccess().getBeamTypeAssignment_3(), "rule__ModelBmodesbmi__BeamTypeAssignment_3");
					put(grammarAccess.getModelBmodesbmiAccess().getRotRpmAssignment_4(), "rule__ModelBmodesbmi__RotRpmAssignment_4");
					put(grammarAccess.getModelBmodesbmiAccess().getRpmMultAssignment_5(), "rule__ModelBmodesbmi__RpmMultAssignment_5");
					put(grammarAccess.getModelBmodesbmiAccess().getRadiusAssignment_6(), "rule__ModelBmodesbmi__RadiusAssignment_6");
					put(grammarAccess.getModelBmodesbmiAccess().getHubRadAssignment_7(), "rule__ModelBmodesbmi__HubRadAssignment_7");
					put(grammarAccess.getModelBmodesbmiAccess().getPreConeAssignment_8(), "rule__ModelBmodesbmi__PreConeAssignment_8");
					put(grammarAccess.getModelBmodesbmiAccess().getBlThpAssignment_9(), "rule__ModelBmodesbmi__BlThpAssignment_9");
					put(grammarAccess.getModelBmodesbmiAccess().getHubConnAssignment_10(), "rule__ModelBmodesbmi__HubConnAssignment_10");
					put(grammarAccess.getModelBmodesbmiAccess().getModePrAssignment_11(), "rule__ModelBmodesbmi__ModePrAssignment_11");
					put(grammarAccess.getModelBmodesbmiAccess().getTabDelimAssignment_12(), "rule__ModelBmodesbmi__TabDelimAssignment_12");
					put(grammarAccess.getModelBmodesbmiAccess().getMidNodeTwAssignment_13(), "rule__ModelBmodesbmi__MidNodeTwAssignment_13");
					put(grammarAccess.getModelBmodesbmiAccess().getSecAssignment_15(), "rule__ModelBmodesbmi__SecAssignment_15");
					put(grammarAccess.getModelBmodesbmiAccess().getTipMassAssignment_16(), "rule__ModelBmodesbmi__TipMassAssignment_16");
					put(grammarAccess.getModelBmodesbmiAccess().getCmLocAssignment_17(), "rule__ModelBmodesbmi__CmLocAssignment_17");
					put(grammarAccess.getModelBmodesbmiAccess().getCmAxialAssignment_18(), "rule__ModelBmodesbmi__CmAxialAssignment_18");
					put(grammarAccess.getModelBmodesbmiAccess().getIxxTipAssignment_19(), "rule__ModelBmodesbmi__IxxTipAssignment_19");
					put(grammarAccess.getModelBmodesbmiAccess().getIyyTipAssignment_20(), "rule__ModelBmodesbmi__IyyTipAssignment_20");
					put(grammarAccess.getModelBmodesbmiAccess().getIzzTipAssignment_21(), "rule__ModelBmodesbmi__IzzTipAssignment_21");
					put(grammarAccess.getModelBmodesbmiAccess().getIxyTipAssignment_22(), "rule__ModelBmodesbmi__IxyTipAssignment_22");
					put(grammarAccess.getModelBmodesbmiAccess().getIzxTipAssignment_23(), "rule__ModelBmodesbmi__IzxTipAssignment_23");
					put(grammarAccess.getModelBmodesbmiAccess().getIyzTipAssignment_24(), "rule__ModelBmodesbmi__IyzTipAssignment_24");
					put(grammarAccess.getModelBmodesbmiAccess().getSecAssignment_26(), "rule__ModelBmodesbmi__SecAssignment_26");
					put(grammarAccess.getModelBmodesbmiAccess().getIdMatAssignment_27(), "rule__ModelBmodesbmi__IdMatAssignment_27");
					put(grammarAccess.getModelBmodesbmiAccess().getSecFileAssignment_28(), "rule__ModelBmodesbmi__SecFileAssignment_28");
					put(grammarAccess.getModelBmodesbmiAccess().getSecAssignment_30(), "rule__ModelBmodesbmi__SecAssignment_30");
					put(grammarAccess.getModelBmodesbmiAccess().getSecMasMultAssignment_31(), "rule__ModelBmodesbmi__SecMasMultAssignment_31");
					put(grammarAccess.getModelBmodesbmiAccess().getFlpInrMultAssignment_32(), "rule__ModelBmodesbmi__FlpInrMultAssignment_32");
					put(grammarAccess.getModelBmodesbmiAccess().getLagInrMultAssignment_33(), "rule__ModelBmodesbmi__LagInrMultAssignment_33");
					put(grammarAccess.getModelBmodesbmiAccess().getFlpstfMultAssignment_34(), "rule__ModelBmodesbmi__FlpstfMultAssignment_34");
					put(grammarAccess.getModelBmodesbmiAccess().getEdgStfMultAssignment_35(), "rule__ModelBmodesbmi__EdgStfMultAssignment_35");
					put(grammarAccess.getModelBmodesbmiAccess().getTorStfMultAssignment_36(), "rule__ModelBmodesbmi__TorStfMultAssignment_36");
					put(grammarAccess.getModelBmodesbmiAccess().getAxiStfMultAssignment_37(), "rule__ModelBmodesbmi__AxiStfMultAssignment_37");
					put(grammarAccess.getModelBmodesbmiAccess().getCgOffsMultAssignment_38(), "rule__ModelBmodesbmi__CgOffsMultAssignment_38");
					put(grammarAccess.getModelBmodesbmiAccess().getScOffsMultAssignment_39(), "rule__ModelBmodesbmi__ScOffsMultAssignment_39");
					put(grammarAccess.getModelBmodesbmiAccess().getTcOffsMultAssignment_40(), "rule__ModelBmodesbmi__TcOffsMultAssignment_40");
					put(grammarAccess.getModelBmodesbmiAccess().getSecAssignment_42(), "rule__ModelBmodesbmi__SecAssignment_42");
					put(grammarAccess.getModelBmodesbmiAccess().getNSeltAssignment_43(), "rule__ModelBmodesbmi__NSeltAssignment_43");
					put(grammarAccess.getModelBmodesbmiAccess().getSecAssignment_44(), "rule__ModelBmodesbmi__SecAssignment_44");
					put(grammarAccess.getModelBmodesbmiAccess().getElLocAssignment_45(), "rule__ModelBmodesbmi__ElLocAssignment_45");
					put(grammarAccess.getModelBmodesbmiAccess().getSecAssignment_47(), "rule__ModelBmodesbmi__SecAssignment_47");
					put(grammarAccess.getModelBmodesbmiAccess().getTwrSupportAssignment_48(), "rule__ModelBmodesbmi__TwrSupportAssignment_48");
					put(grammarAccess.getModelBmodesbmiAccess().getSecAssignment_49(), "rule__ModelBmodesbmi__SecAssignment_49");
					put(grammarAccess.getModelBmodesbmiAccess().getTwrAttachAssignment_50(), "rule__ModelBmodesbmi__TwrAttachAssignment_50");
					put(grammarAccess.getModelBmodesbmiAccess().getTwrWiresAssignment_51(), "rule__ModelBmodesbmi__TwrWiresAssignment_51");
					put(grammarAccess.getModelBmodesbmiAccess().getNodeAttachAssignment_52(), "rule__ModelBmodesbmi__NodeAttachAssignment_52");
					put(grammarAccess.getModelBmodesbmiAccess().getWireStiffAssignment_53(), "rule__ModelBmodesbmi__WireStiffAssignment_53");
					put(grammarAccess.getModelBmodesbmiAccess().getWireAngleAssignment_54(), "rule__ModelBmodesbmi__WireAngleAssignment_54");
					put(grammarAccess.getHeaderAccess().getNameAssignment_0(), "rule__Header__NameAssignment_0");
					put(grammarAccess.getHeaderAccess().getDescAssignment_2(), "rule__Header__DescAssignment_2");
					put(grammarAccess.getSectionAccess().getNameAssignment_0(), "rule__Section__NameAssignment_0");
					put(grammarAccess.getBEchoAccess().getValueAssignment_1(), "rule__BEcho__ValueAssignment_1");
					put(grammarAccess.getBEchoAccess().getNameAssignment_3(), "rule__BEcho__NameAssignment_3");
					put(grammarAccess.getIBeamTypeAccess().getValueAssignment_1(), "rule__IBeamType__ValueAssignment_1");
					put(grammarAccess.getIBeamTypeAccess().getNameAssignment_3(), "rule__IBeamType__NameAssignment_3");
					put(grammarAccess.getNRotRpmAccess().getValueAssignment_1(), "rule__NRotRpm__ValueAssignment_1");
					put(grammarAccess.getNRotRpmAccess().getNameAssignment_3(), "rule__NRotRpm__NameAssignment_3");
					put(grammarAccess.getNRpmMultAccess().getValueAssignment_1(), "rule__NRpmMult__ValueAssignment_1");
					put(grammarAccess.getNRpmMultAccess().getNameAssignment_3(), "rule__NRpmMult__NameAssignment_3");
					put(grammarAccess.getNRadiusAccess().getValueAssignment_1(), "rule__NRadius__ValueAssignment_1");
					put(grammarAccess.getNRadiusAccess().getNameAssignment_3(), "rule__NRadius__NameAssignment_3");
					put(grammarAccess.getNHubRadAccess().getValueAssignment_1(), "rule__NHubRad__ValueAssignment_1");
					put(grammarAccess.getNHubRadAccess().getNameAssignment_3(), "rule__NHubRad__NameAssignment_3");
					put(grammarAccess.getNPreconeAccess().getValueAssignment_1(), "rule__NPrecone__ValueAssignment_1");
					put(grammarAccess.getNPreconeAccess().getNameAssignment_3(), "rule__NPrecone__NameAssignment_3");
					put(grammarAccess.getNBlThpAccess().getValueAssignment_1(), "rule__NBlThp__ValueAssignment_1");
					put(grammarAccess.getNBlThpAccess().getNameAssignment_3(), "rule__NBlThp__NameAssignment_3");
					put(grammarAccess.getIHubConnAccess().getValueAssignment_1(), "rule__IHubConn__ValueAssignment_1");
					put(grammarAccess.getIHubConnAccess().getNameAssignment_3(), "rule__IHubConn__NameAssignment_3");
					put(grammarAccess.getIModePrAccess().getValueAssignment_1(), "rule__IModePr__ValueAssignment_1");
					put(grammarAccess.getIModePrAccess().getNameAssignment_3(), "rule__IModePr__NameAssignment_3");
					put(grammarAccess.getBTabDelimAccess().getValueAssignment_1(), "rule__BTabDelim__ValueAssignment_1");
					put(grammarAccess.getBTabDelimAccess().getNameAssignment_3(), "rule__BTabDelim__NameAssignment_3");
					put(grammarAccess.getBMidNodeTwAccess().getValueAssignment_1(), "rule__BMidNodeTw__ValueAssignment_1");
					put(grammarAccess.getBMidNodeTwAccess().getNameAssignment_3(), "rule__BMidNodeTw__NameAssignment_3");
					put(grammarAccess.getNTipMassAccess().getValueAssignment_1(), "rule__NTipMass__ValueAssignment_1");
					put(grammarAccess.getNTipMassAccess().getNameAssignment_3(), "rule__NTipMass__NameAssignment_3");
					put(grammarAccess.getNCmLocAccess().getValueAssignment_1(), "rule__NCmLoc__ValueAssignment_1");
					put(grammarAccess.getNCmLocAccess().getNameAssignment_3(), "rule__NCmLoc__NameAssignment_3");
					put(grammarAccess.getNCmAxialAccess().getValueAssignment_1(), "rule__NCmAxial__ValueAssignment_1");
					put(grammarAccess.getNCmAxialAccess().getNameAssignment_3(), "rule__NCmAxial__NameAssignment_3");
					put(grammarAccess.getNIxxTipAccess().getValueAssignment_1(), "rule__NIxxTip__ValueAssignment_1");
					put(grammarAccess.getNIxxTipAccess().getNameAssignment_3(), "rule__NIxxTip__NameAssignment_3");
					put(grammarAccess.getNIyyTipAccess().getValueAssignment_1(), "rule__NIyyTip__ValueAssignment_1");
					put(grammarAccess.getNIyyTipAccess().getNameAssignment_3(), "rule__NIyyTip__NameAssignment_3");
					put(grammarAccess.getNIzzTipAccess().getValueAssignment_1(), "rule__NIzzTip__ValueAssignment_1");
					put(grammarAccess.getNIzzTipAccess().getNameAssignment_3(), "rule__NIzzTip__NameAssignment_3");
					put(grammarAccess.getNIxyTipAccess().getValueAssignment_1(), "rule__NIxyTip__ValueAssignment_1");
					put(grammarAccess.getNIxyTipAccess().getNameAssignment_3(), "rule__NIxyTip__NameAssignment_3");
					put(grammarAccess.getNIzxTipAccess().getValueAssignment_1(), "rule__NIzxTip__ValueAssignment_1");
					put(grammarAccess.getNIzxTipAccess().getNameAssignment_3(), "rule__NIzxTip__NameAssignment_3");
					put(grammarAccess.getNIyzTipAccess().getValueAssignment_1(), "rule__NIyzTip__ValueAssignment_1");
					put(grammarAccess.getNIyzTipAccess().getNameAssignment_3(), "rule__NIyzTip__NameAssignment_3");
					put(grammarAccess.getIIdMatAccess().getValueAssignment_1(), "rule__IIdMat__ValueAssignment_1");
					put(grammarAccess.getIIdMatAccess().getNameAssignment_3(), "rule__IIdMat__NameAssignment_3");
					put(grammarAccess.getISecFileAccess().getValueAssignment_1(), "rule__ISecFile__ValueAssignment_1");
					put(grammarAccess.getISecFileAccess().getNameAssignment_3(), "rule__ISecFile__NameAssignment_3");
					put(grammarAccess.getNSecMasMultAccess().getValueAssignment_1(), "rule__NSecMasMult__ValueAssignment_1");
					put(grammarAccess.getNSecMasMultAccess().getNameAssignment_3(), "rule__NSecMasMult__NameAssignment_3");
					put(grammarAccess.getNFlpInrMultAccess().getValueAssignment_1(), "rule__NFlpInrMult__ValueAssignment_1");
					put(grammarAccess.getNFlpInrMultAccess().getNameAssignment_3(), "rule__NFlpInrMult__NameAssignment_3");
					put(grammarAccess.getNLagInrMultAccess().getValueAssignment_1(), "rule__NLagInrMult__ValueAssignment_1");
					put(grammarAccess.getNLagInrMultAccess().getNameAssignment_3(), "rule__NLagInrMult__NameAssignment_3");
					put(grammarAccess.getNFlpstfMultAccess().getValueAssignment_1(), "rule__NFlpstfMult__ValueAssignment_1");
					put(grammarAccess.getNFlpstfMultAccess().getNameAssignment_3(), "rule__NFlpstfMult__NameAssignment_3");
					put(grammarAccess.getNEdgStfMultAccess().getValueAssignment_1(), "rule__NEdgStfMult__ValueAssignment_1");
					put(grammarAccess.getNEdgStfMultAccess().getNameAssignment_3(), "rule__NEdgStfMult__NameAssignment_3");
					put(grammarAccess.getNTorStfMultAccess().getValueAssignment_1(), "rule__NTorStfMult__ValueAssignment_1");
					put(grammarAccess.getNTorStfMultAccess().getNameAssignment_3(), "rule__NTorStfMult__NameAssignment_3");
					put(grammarAccess.getNAxiStfMultAccess().getValueAssignment_1(), "rule__NAxiStfMult__ValueAssignment_1");
					put(grammarAccess.getNAxiStfMultAccess().getNameAssignment_3(), "rule__NAxiStfMult__NameAssignment_3");
					put(grammarAccess.getNCgOffsMultAccess().getValueAssignment_1(), "rule__NCgOffsMult__ValueAssignment_1");
					put(grammarAccess.getNCgOffsMultAccess().getNameAssignment_3(), "rule__NCgOffsMult__NameAssignment_3");
					put(grammarAccess.getNScOffsMultAccess().getValueAssignment_1(), "rule__NScOffsMult__ValueAssignment_1");
					put(grammarAccess.getNScOffsMultAccess().getNameAssignment_3(), "rule__NScOffsMult__NameAssignment_3");
					put(grammarAccess.getNTcOffsMultAccess().getValueAssignment_1(), "rule__NTcOffsMult__ValueAssignment_1");
					put(grammarAccess.getNTcOffsMultAccess().getNameAssignment_3(), "rule__NTcOffsMult__NameAssignment_3");
					put(grammarAccess.getINSeltAccess().getValueAssignment_1(), "rule__INSelt__ValueAssignment_1");
					put(grammarAccess.getINSeltAccess().getNameAssignment_3(), "rule__INSelt__NameAssignment_3");
					put(grammarAccess.getAElLocAccess().getEl_locAssignment_1_0(), "rule__AElLoc__El_locAssignment_1_0");
					put(grammarAccess.getAElLocAccess().getEl_locAssignment_2(), "rule__AElLoc__El_locAssignment_2");
					put(grammarAccess.getITwrSupportAccess().getValueAssignment_1(), "rule__ITwrSupport__ValueAssignment_1");
					put(grammarAccess.getITwrSupportAccess().getNameAssignment_3(), "rule__ITwrSupport__NameAssignment_3");
					put(grammarAccess.getITwrAttachAccess().getValueAssignment_1(), "rule__ITwrAttach__ValueAssignment_1");
					put(grammarAccess.getITwrAttachAccess().getNameAssignment_3(), "rule__ITwrAttach__NameAssignment_3");
					put(grammarAccess.getATwrWiresAccess().getEl_locAssignment_1_0(), "rule__ATwrWires__El_locAssignment_1_0");
					put(grammarAccess.getATwrWiresAccess().getNameAssignment_2(), "rule__ATwrWires__NameAssignment_2");
					put(grammarAccess.getANodeAttachAccess().getEl_locAssignment_1_0(), "rule__ANodeAttach__El_locAssignment_1_0");
					put(grammarAccess.getANodeAttachAccess().getNameAssignment_2(), "rule__ANodeAttach__NameAssignment_2");
					put(grammarAccess.getAWireStiffAccess().getEl_locAssignment_1_0(), "rule__AWireStiff__El_locAssignment_1_0");
					put(grammarAccess.getAWireStiffAccess().getNameAssignment_2(), "rule__AWireStiff__NameAssignment_2");
					put(grammarAccess.getAWireAngleAccess().getEl_locAssignment_1_0(), "rule__AWireAngle__El_locAssignment_1_0");
					put(grammarAccess.getAWireAngleAccess().getNameAssignment_2(), "rule__AWireAngle__NameAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			sc.ndt.editor.bmodes.ui.contentassist.antlr.internal.InternalBmodesbmiParser typedParser = (sc.ndt.editor.bmodes.ui.contentassist.antlr.internal.InternalBmodesbmiParser) parser;
			typedParser.entryRuleModelBmodesbmi();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] {  };
	}
	
	public BmodesbmiGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BmodesbmiGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
