/*
* generated by Xtext
*/
grammar InternalFastadn;

options {
	superClass=AbstractInternalAntlrParser;
	
}

@lexer::header {
package sc.ndt.editor.fast.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package sc.ndt.editor.fast.parser.antlr.internal; 

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import sc.ndt.editor.fast.services.FastadnGrammarAccess;

}

@parser::members {

 	private FastadnGrammarAccess grammarAccess;
 	
    public InternalFastadnParser(TokenStream input, FastadnGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }
    
    @Override
    protected String getFirstRuleName() {
    	return "ModelFastadn";	
   	}
   	
   	@Override
   	protected FastadnGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}
}

@rulecatch { 
    catch (RecognitionException re) { 
        recover(input,re); 
        appendSkippedTokens();
    } 
}




// Entry rule entryRuleModelFastadn
entryRuleModelFastadn returns [EObject current=null] 
	:
	{ newCompositeNode(grammarAccess.getModelFastadnRule()); }
	 iv_ruleModelFastadn=ruleModelFastadn 
	 { $current=$iv_ruleModelFastadn.current; } 
	 EOF 
;

// Rule ModelFastadn
ruleModelFastadn returns [EObject current=null] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
((
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getHeadHeaderParserRuleCall_0_0()); 
	    }
		lv_Head_0_0=ruleHeader		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"Head",
        		lv_Head_0_0, 
        		"Header");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getSIUnitsSUnitsParserRuleCall_1_0()); 
	    }
		lv_SIUnits_1_0=rulesUnits		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"SIUnits",
        		lv_SIUnits_1_0, 
        		"sUnits");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getStallModSStallModParserRuleCall_2_0()); 
	    }
		lv_StallMod_2_0=rulesStallMod		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"StallMod",
        		lv_StallMod_2_0, 
        		"sStallMod");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getUseCmSUseCmParserRuleCall_3_0()); 
	    }
		lv_UseCm_3_0=rulesUseCm		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"UseCm",
        		lv_UseCm_3_0, 
        		"sUseCm");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getInfModelSInfModelParserRuleCall_4_0()); 
	    }
		lv_InfModel_4_0=rulesInfModel		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"InfModel",
        		lv_InfModel_4_0, 
        		"sInfModel");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getIndModelSIndModelParserRuleCall_5_0()); 
	    }
		lv_IndModel_5_0=rulesIndModel		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"IndModel",
        		lv_IndModel_5_0, 
        		"sIndModel");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getAtolerNAtolerParserRuleCall_6_0()); 
	    }
		lv_Atoler_6_0=rulenAtoler		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"Atoler",
        		lv_Atoler_6_0, 
        		"nAtoler");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getTLModelSTLModelParserRuleCall_7_0()); 
	    }
		lv_TLModel_7_0=rulesTLModel		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"TLModel",
        		lv_TLModel_7_0, 
        		"sTLModel");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getHLModelSHLModelParserRuleCall_8_0()); 
	    }
		lv_HLModel_8_0=rulesHLModel		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"HLModel",
        		lv_HLModel_8_0, 
        		"sHLModel");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getWindFileFWindFileParserRuleCall_9_0()); 
	    }
		lv_WindFile_9_0=rulefWindFile		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"WindFile",
        		lv_WindFile_9_0, 
        		"fWindFile");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getHHNHHParserRuleCall_10_0()); 
	    }
		lv_HH_10_0=rulenHH		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"HH",
        		lv_HH_10_0, 
        		"nHH");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getTwrShadNTwrShadParserRuleCall_11_0()); 
	    }
		lv_TwrShad_11_0=rulenTwrShad		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"TwrShad",
        		lv_TwrShad_11_0, 
        		"nTwrShad");
	        afterParserOrEnumRuleCall();
	    }

)
)((
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getShadHWidNShadHWidParserRuleCall_12_0_0()); 
	    }
		lv_ShadHWid_12_0=rulenShadHWid		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"ShadHWid",
        		lv_ShadHWid_12_0, 
        		"nShadHWid");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getTShadRefPtNTShadRefPtParserRuleCall_12_1_0()); 
	    }
		lv_TShadRefPt_13_0=rulenTShadRefPt		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"TShadRefPt",
        		lv_TShadRefPt_13_0, 
        		"nTShadRefPt");
	        afterParserOrEnumRuleCall();
	    }

)
))(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getRhoNRhoParserRuleCall_13_0()); 
	    }
		lv_Rho_14_0=rulenRho		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"Rho",
        		lv_Rho_14_0, 
        		"nRho");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getKinViscNKinViscParserRuleCall_14_0()); 
	    }
		lv_KinVisc_15_0=rulenKinVisc		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"KinVisc",
        		lv_KinVisc_15_0, 
        		"nKinVisc");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getDTAeroNDTAeroParserRuleCall_15_0()); 
	    }
		lv_DTAero_16_0=rulenDTAero		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"DTAero",
        		lv_DTAero_16_0, 
        		"nDTAero");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getNumFoilINumFoilParserRuleCall_16_0()); 
	    }
		lv_NumFoil_17_0=ruleiNumFoil		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"NumFoil",
        		lv_NumFoil_17_0, 
        		"iNumFoil");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getFoilNmAAirfoilListParserRuleCall_17_0()); 
	    }
		lv_FoilNm_18_0=ruleaAirfoilList		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"FoilNm",
        		lv_FoilNm_18_0, 
        		"aAirfoilList");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getBldNodesIBldNodesParserRuleCall_18_0()); 
	    }
		lv_BldNodes_19_0=ruleiBldNodes		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"BldNodes",
        		lv_BldNodes_19_0, 
        		"iBldNodes");
	        afterParserOrEnumRuleCall();
	    }

)
)(
(
		{ 
	        newCompositeNode(grammarAccess.getModelFastadnAccess().getAirStatAAirStatParserRuleCall_19_0()); 
	    }
		lv_AirStat_20_0=ruleaAirStat		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getModelFastadnRule());
	        }
       		set(
       			$current, 
       			"AirStat",
        		lv_AirStat_20_0, 
        		"aAirStat");
	        afterParserOrEnumRuleCall();
	    }

)
)(this_WS_21=RULE_WS
    { 
    newLeafNode(this_WS_21, grammarAccess.getModelFastadnAccess().getWSTerminalRuleCall_20_0()); 
    }

    |this_NEWLINE_22=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_22, grammarAccess.getModelFastadnAccess().getNEWLINETerminalRuleCall_20_1()); 
    }

    |this_SL_COMMENT_23=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_23, grammarAccess.getModelFastadnAccess().getSL_COMMENTTerminalRuleCall_20_2()); 
    }
)*)
;





// Entry rule entryRuletNUMBER
entryRuletNUMBER returns [String current=null] 
	:
	{ newCompositeNode(grammarAccess.getTNUMBERRule()); } 
	 iv_ruletNUMBER=ruletNUMBER 
	 { $current=$iv_ruletNUMBER.current.getText(); }  
	 EOF 
;

// Rule tNUMBER
ruletNUMBER returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(    this_INT_0=RULE_INT    {
		$current.merge(this_INT_0);
    }

    { 
    newLeafNode(this_INT_0, grammarAccess.getTNUMBERAccess().getINTTerminalRuleCall_0()); 
    }

    |    this_NUMBER_1=RULE_NUMBER    {
		$current.merge(this_NUMBER_1);
    }

    { 
    newLeafNode(this_NUMBER_1, grammarAccess.getTNUMBERAccess().getNUMBERTerminalRuleCall_1()); 
    }
)
    ;





// Entry rule entryRuletBOOL
entryRuletBOOL returns [String current=null] 
	:
	{ newCompositeNode(grammarAccess.getTBOOLRule()); } 
	 iv_ruletBOOL=ruletBOOL 
	 { $current=$iv_ruletBOOL.current.getText(); }  
	 EOF 
;

// Rule tBOOL
ruletBOOL returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()] 
    @init { enterRule(); 
    }
    @after { leaveRule(); }:
(
	kw='TRUE' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getTBOOLAccess().getTRUEKeyword_0()); 
    }

    |
	kw='True' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getTBOOLAccess().getTrueKeyword_1()); 
    }

    |
	kw='true' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getTBOOLAccess().getTrueKeyword_2()); 
    }

    |
	kw='FALSE' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getTBOOLAccess().getFALSEKeyword_3()); 
    }

    |
	kw='False' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getTBOOLAccess().getFalseKeyword_4()); 
    }

    |
	kw='false' 
    {
        $current.merge(kw);
        newLeafNode(kw, grammarAccess.getTBOOLAccess().getFalseKeyword_5()); 
    }
)
    ;







// Entry rule entryRuleHeader
entryRuleHeader returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getHeaderRule()); }
	 iv_ruleHeader=ruleHeader 
	 { $current=$iv_ruleHeader.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule Header
ruleHeader returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((
(
		lv_name_0_0=RULE_SL_COMMENT
		{
			newLeafNode(lv_name_0_0, grammarAccess.getHeaderAccess().getNameSL_COMMENTTerminalRuleCall_0_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getHeaderRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"name",
        		lv_name_0_0, 
        		"SL_COMMENT");
	    }

)
)this_NEWLINE_1=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_1, grammarAccess.getHeaderAccess().getNEWLINETerminalRuleCall_1()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulesUnits
entryRulesUnits returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getSUnitsRule()); }
	 iv_rulesUnits=rulesUnits 
	 { $current=$iv_rulesUnits.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule sUnits
rulesUnits returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getSUnitsAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		lv_value_1_0=RULE_UNITS
		{
			newLeafNode(lv_value_1_0, grammarAccess.getSUnitsAccess().getValueUNITSTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSUnitsRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"UNITS");
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getSUnitsAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'SysUnits' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getSUnitsAccess().getNameSysUnitsKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSUnitsRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "SysUnits");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getSUnitsAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getSUnitsAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getSUnitsAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulesStallMod
entryRulesStallMod returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getSStallModRule()); }
	 iv_rulesStallMod=rulesStallMod 
	 { $current=$iv_rulesStallMod.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule sStallMod
rulesStallMod returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getSStallModAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		lv_value_1_0=RULE_STALL
		{
			newLeafNode(lv_value_1_0, grammarAccess.getSStallModAccess().getValueSTALLTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSStallModRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"STALL");
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getSStallModAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'StallMod' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getSStallModAccess().getNameStallModKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSStallModRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "StallMod");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getSStallModAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getSStallModAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getSStallModAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulesUseCm
entryRulesUseCm returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getSUseCmRule()); }
	 iv_rulesUseCm=rulesUseCm 
	 { $current=$iv_rulesUseCm.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule sUseCm
rulesUseCm returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getSUseCmAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		lv_value_1_0=RULE_CM
		{
			newLeafNode(lv_value_1_0, grammarAccess.getSUseCmAccess().getValueCMTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSUseCmRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"CM");
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getSUseCmAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'UseCm' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getSUseCmAccess().getNameUseCmKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSUseCmRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "UseCm");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getSUseCmAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getSUseCmAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getSUseCmAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulesInfModel
entryRulesInfModel returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getSInfModelRule()); }
	 iv_rulesInfModel=rulesInfModel 
	 { $current=$iv_rulesInfModel.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule sInfModel
rulesInfModel returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getSInfModelAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		lv_value_1_0=RULE_INFMODEL
		{
			newLeafNode(lv_value_1_0, grammarAccess.getSInfModelAccess().getValueINFMODELTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSInfModelRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"INFMODEL");
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getSInfModelAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'InfModel' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getSInfModelAccess().getNameInfModelKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSInfModelRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "InfModel");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getSInfModelAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getSInfModelAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getSInfModelAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulesIndModel
entryRulesIndModel returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getSIndModelRule()); }
	 iv_rulesIndModel=rulesIndModel 
	 { $current=$iv_rulesIndModel.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule sIndModel
rulesIndModel returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getSIndModelAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		lv_value_1_0=RULE_INDMODEL
		{
			newLeafNode(lv_value_1_0, grammarAccess.getSIndModelAccess().getValueINDMODELTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSIndModelRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"INDMODEL");
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getSIndModelAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'IndModel' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getSIndModelAccess().getNameIndModelKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSIndModelRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "IndModel");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getSIndModelAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getSIndModelAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getSIndModelAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulenAtoler
entryRulenAtoler returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getNAtolerRule()); }
	 iv_rulenAtoler=rulenAtoler 
	 { $current=$iv_rulenAtoler.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule nAtoler
rulenAtoler returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getNAtolerAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		{ 
	        newCompositeNode(grammarAccess.getNAtolerAccess().getValueTNUMBERParserRuleCall_1_0()); 
	    }
		lv_value_1_0=ruletNUMBER		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getNAtolerRule());
	        }
       		set(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"tNUMBER");
	        afterParserOrEnumRuleCall();
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getNAtolerAccess().getWSTerminalRuleCall_2()); 
    }
(
(
(
		lv_name_3_1=	'Atoler' 
    {
        newLeafNode(lv_name_3_1, grammarAccess.getNAtolerAccess().getNameAtolerKeyword_3_0_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getNAtolerRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_1, null);
	    }

    |		lv_name_3_2=	'AToler' 
    {
        newLeafNode(lv_name_3_2, grammarAccess.getNAtolerAccess().getNameATolerKeyword_3_0_1());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getNAtolerRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_2, null);
	    }

)

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getNAtolerAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getNAtolerAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getNAtolerAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulesTLModel
entryRulesTLModel returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getSTLModelRule()); }
	 iv_rulesTLModel=rulesTLModel 
	 { $current=$iv_rulesTLModel.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule sTLModel
rulesTLModel returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getSTLModelAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		lv_value_1_0=RULE_PRANDTL
		{
			newLeafNode(lv_value_1_0, grammarAccess.getSTLModelAccess().getValuePRANDTLTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSTLModelRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"PRANDTL");
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getSTLModelAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'TLModel' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getSTLModelAccess().getNameTLModelKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSTLModelRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "TLModel");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getSTLModelAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getSTLModelAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getSTLModelAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulesHLModel
entryRulesHLModel returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getSHLModelRule()); }
	 iv_rulesHLModel=rulesHLModel 
	 { $current=$iv_rulesHLModel.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule sHLModel
rulesHLModel returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getSHLModelAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		lv_value_1_0=RULE_PRANDTL
		{
			newLeafNode(lv_value_1_0, grammarAccess.getSHLModelAccess().getValuePRANDTLTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSHLModelRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"PRANDTL");
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getSHLModelAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'HLModel' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getSHLModelAccess().getNameHLModelKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getSHLModelRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "HLModel");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getSHLModelAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getSHLModelAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getSHLModelAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulefWindFile
entryRulefWindFile returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getFWindFileRule()); }
	 iv_rulefWindFile=rulefWindFile 
	 { $current=$iv_rulefWindFile.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule fWindFile
rulefWindFile returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getFWindFileAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		lv_value_1_0=RULE_STRING
		{
			newLeafNode(lv_value_1_0, grammarAccess.getFWindFileAccess().getValueSTRINGTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getFWindFileRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"STRING");
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getFWindFileAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'WindFile' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getFWindFileAccess().getNameWindFileKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getFWindFileRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "WindFile");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getFWindFileAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getFWindFileAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getFWindFileAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulenHH
entryRulenHH returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getNHHRule()); }
	 iv_rulenHH=rulenHH 
	 { $current=$iv_rulenHH.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule nHH
rulenHH returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getNHHAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		{ 
	        newCompositeNode(grammarAccess.getNHHAccess().getValueTNUMBERParserRuleCall_1_0()); 
	    }
		lv_value_1_0=ruletNUMBER		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getNHHRule());
	        }
       		set(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"tNUMBER");
	        afterParserOrEnumRuleCall();
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getNHHAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'HH' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getNHHAccess().getNameHHKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getNHHRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "HH");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getNHHAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getNHHAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getNHHAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulenTwrShad
entryRulenTwrShad returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getNTwrShadRule()); }
	 iv_rulenTwrShad=rulenTwrShad 
	 { $current=$iv_rulenTwrShad.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule nTwrShad
rulenTwrShad returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getNTwrShadAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		{ 
	        newCompositeNode(grammarAccess.getNTwrShadAccess().getValueTNUMBERParserRuleCall_1_0()); 
	    }
		lv_value_1_0=ruletNUMBER		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getNTwrShadRule());
	        }
       		set(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"tNUMBER");
	        afterParserOrEnumRuleCall();
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getNTwrShadAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'TwrShad' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getNTwrShadAccess().getNameTwrShadKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getNTwrShadRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "TwrShad");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getNTwrShadAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getNTwrShadAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getNTwrShadAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}













// Entry rule entryRulenShadHWid
entryRulenShadHWid returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getNShadHWidRule()); }
	 iv_rulenShadHWid=rulenShadHWid 
	 { $current=$iv_rulenShadHWid.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule nShadHWid
rulenShadHWid returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getNShadHWidAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		{ 
	        newCompositeNode(grammarAccess.getNShadHWidAccess().getValueTNUMBERParserRuleCall_1_0()); 
	    }
		lv_value_1_0=ruletNUMBER		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getNShadHWidRule());
	        }
       		set(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"tNUMBER");
	        afterParserOrEnumRuleCall();
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getNShadHWidAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'ShadHWid' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getNShadHWidAccess().getNameShadHWidKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getNShadHWidRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "ShadHWid");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getNShadHWidAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getNShadHWidAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getNShadHWidAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulenTShadRefPt
entryRulenTShadRefPt returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getNTShadRefPtRule()); }
	 iv_rulenTShadRefPt=rulenTShadRefPt 
	 { $current=$iv_rulenTShadRefPt.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule nTShadRefPt
rulenTShadRefPt returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getNTShadRefPtAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		{ 
	        newCompositeNode(grammarAccess.getNTShadRefPtAccess().getValueTNUMBERParserRuleCall_1_0()); 
	    }
		lv_value_1_0=ruletNUMBER		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getNTShadRefPtRule());
	        }
       		set(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"tNUMBER");
	        afterParserOrEnumRuleCall();
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getNTShadRefPtAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'T_Shad_Refpt' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getNTShadRefPtAccess().getNameT_Shad_RefptKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getNTShadRefPtRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "T_Shad_Refpt");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getNTShadRefPtAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getNTShadRefPtAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getNTShadRefPtAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulenRho
entryRulenRho returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getNRhoRule()); }
	 iv_rulenRho=rulenRho 
	 { $current=$iv_rulenRho.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule nRho
rulenRho returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getNRhoAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		{ 
	        newCompositeNode(grammarAccess.getNRhoAccess().getValueTNUMBERParserRuleCall_1_0()); 
	    }
		lv_value_1_0=ruletNUMBER		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getNRhoRule());
	        }
       		set(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"tNUMBER");
	        afterParserOrEnumRuleCall();
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getNRhoAccess().getWSTerminalRuleCall_2()); 
    }
(
(
(
		lv_name_3_1=	'Rho' 
    {
        newLeafNode(lv_name_3_1, grammarAccess.getNRhoAccess().getNameRhoKeyword_3_0_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getNRhoRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_1, null);
	    }

    |		lv_name_3_2=	'AirDens' 
    {
        newLeafNode(lv_name_3_2, grammarAccess.getNRhoAccess().getNameAirDensKeyword_3_0_1());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getNRhoRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_2, null);
	    }

)

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getNRhoAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getNRhoAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getNRhoAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulenKinVisc
entryRulenKinVisc returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getNKinViscRule()); }
	 iv_rulenKinVisc=rulenKinVisc 
	 { $current=$iv_rulenKinVisc.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule nKinVisc
rulenKinVisc returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getNKinViscAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		{ 
	        newCompositeNode(grammarAccess.getNKinViscAccess().getValueTNUMBERParserRuleCall_1_0()); 
	    }
		lv_value_1_0=ruletNUMBER		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getNKinViscRule());
	        }
       		set(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"tNUMBER");
	        afterParserOrEnumRuleCall();
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getNKinViscAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'KinVisc' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getNKinViscAccess().getNameKinViscKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getNKinViscRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "KinVisc");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getNKinViscAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getNKinViscAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getNKinViscAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRulenDTAero
entryRulenDTAero returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getNDTAeroRule()); }
	 iv_rulenDTAero=rulenDTAero 
	 { $current=$iv_rulenDTAero.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule nDTAero
rulenDTAero returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getNDTAeroAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		{ 
	        newCompositeNode(grammarAccess.getNDTAeroAccess().getValueTNUMBERParserRuleCall_1_0()); 
	    }
		lv_value_1_0=ruletNUMBER		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getNDTAeroRule());
	        }
       		set(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"tNUMBER");
	        afterParserOrEnumRuleCall();
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getNDTAeroAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'DTAero' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getNDTAeroAccess().getNameDTAeroKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getNDTAeroRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "DTAero");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getNDTAeroAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getNDTAeroAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getNDTAeroAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRuleiNumFoil
entryRuleiNumFoil returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getINumFoilRule()); }
	 iv_ruleiNumFoil=ruleiNumFoil 
	 { $current=$iv_ruleiNumFoil.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule iNumFoil
ruleiNumFoil returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getINumFoilAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		lv_value_1_0=RULE_INT
		{
			newLeafNode(lv_value_1_0, grammarAccess.getINumFoilAccess().getValueINTTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getINumFoilRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"INT");
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getINumFoilAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'NumFoil' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getINumFoilAccess().getNameNumFoilKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getINumFoilRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "NumFoil");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getINumFoilAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getINumFoilAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getINumFoilAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRuleaAirfoilList
entryRuleaAirfoilList returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getAAirfoilListRule()); }
	 iv_ruleaAirfoilList=ruleaAirfoilList 
	 { $current=$iv_ruleaAirfoilList.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule aAirfoilList
ruleaAirfoilList returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getAAirfoilListAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		lv_value_1_0=RULE_STRING
		{
			newLeafNode(lv_value_1_0, grammarAccess.getAAirfoilListAccess().getValueSTRINGTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAAirfoilListRule());
	        }
       		addWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"STRING");
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getAAirfoilListAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'FoilNm' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getAAirfoilListAccess().getNameFoilNmKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAAirfoilListRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "FoilNm");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getAAirfoilListAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getAAirfoilListAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getAAirfoilListAccess().getNEWLINETerminalRuleCall_6()); 
    }
((this_WS_7=RULE_WS
    { 
    newLeafNode(this_WS_7, grammarAccess.getAAirfoilListAccess().getWSTerminalRuleCall_7_0()); 
    }
)?(
(
		lv_value_8_0=RULE_STRING
		{
			newLeafNode(lv_value_8_0, grammarAccess.getAAirfoilListAccess().getValueSTRINGTerminalRuleCall_7_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAAirfoilListRule());
	        }
       		addWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_8_0, 
        		"STRING");
	    }

)
)(this_WS_9=RULE_WS
    { 
    newLeafNode(this_WS_9, grammarAccess.getAAirfoilListAccess().getWSTerminalRuleCall_7_2()); 
    }
)?(this_SL_COMMENT_10=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_10, grammarAccess.getAAirfoilListAccess().getSL_COMMENTTerminalRuleCall_7_3()); 
    }
)?this_NEWLINE_11=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_11, grammarAccess.getAAirfoilListAccess().getNEWLINETerminalRuleCall_7_4()); 
    }
)*)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRuleiBldNodes
entryRuleiBldNodes returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getIBldNodesRule()); }
	 iv_ruleiBldNodes=ruleiBldNodes 
	 { $current=$iv_ruleiBldNodes.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule iBldNodes
ruleiBldNodes returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getIBldNodesAccess().getWSTerminalRuleCall_0()); 
    }
)?(
(
		lv_value_1_0=RULE_INT
		{
			newLeafNode(lv_value_1_0, grammarAccess.getIBldNodesAccess().getValueINTTerminalRuleCall_1_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getIBldNodesRule());
	        }
       		setWithLastConsumed(
       			$current, 
       			"value",
        		lv_value_1_0, 
        		"INT");
	    }

)
)this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getIBldNodesAccess().getWSTerminalRuleCall_2()); 
    }
(
(
		lv_name_3_0=	'BldNodes' 
    {
        newLeafNode(lv_name_3_0, grammarAccess.getIBldNodesAccess().getNameBldNodesKeyword_3_0());
    }
 
	    {
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getIBldNodesRule());
	        }
       		setWithLastConsumed($current, "name", lv_name_3_0, "BldNodes");
	    }

)
)(this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getIBldNodesAccess().getWSTerminalRuleCall_4()); 
    }
)?(this_SL_COMMENT_5=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_5, grammarAccess.getIBldNodesAccess().getSL_COMMENTTerminalRuleCall_5()); 
    }
)?this_NEWLINE_6=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_6, grammarAccess.getIBldNodesAccess().getNEWLINETerminalRuleCall_6()); 
    }
)
;
finally {
	myHiddenTokenState.restore();
}





// Entry rule entryRuleaAirStat
entryRuleaAirStat returns [EObject current=null] 
	@init { 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
	}
	:
	{ newCompositeNode(grammarAccess.getAAirStatRule()); }
	 iv_ruleaAirStat=ruleaAirStat 
	 { $current=$iv_ruleaAirStat.current; } 
	 EOF 
;
finally {
	myHiddenTokenState.restore();
}

// Rule aAirStat
ruleaAirStat returns [EObject current=null] 
    @init { enterRule(); 
		HiddenTokens myHiddenTokenState = ((XtextTokenStream)input).setHiddenTokens();
    }
    @after { leaveRule(); }:
((this_WS_0=RULE_WS
    { 
    newLeafNode(this_WS_0, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_0()); 
    }
)?	otherlv_1='RNodes' 
    {
    	newLeafNode(otherlv_1, grammarAccess.getAAirStatAccess().getRNodesKeyword_1());
    }
this_WS_2=RULE_WS
    { 
    newLeafNode(this_WS_2, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_2()); 
    }
	otherlv_3='AeroTwst' 
    {
    	newLeafNode(otherlv_3, grammarAccess.getAAirStatAccess().getAeroTwstKeyword_3());
    }
this_WS_4=RULE_WS
    { 
    newLeafNode(this_WS_4, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_4()); 
    }
	otherlv_5='DRNodes' 
    {
    	newLeafNode(otherlv_5, grammarAccess.getAAirStatAccess().getDRNodesKeyword_5());
    }
this_WS_6=RULE_WS
    { 
    newLeafNode(this_WS_6, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_6()); 
    }
	otherlv_7='Chord' 
    {
    	newLeafNode(otherlv_7, grammarAccess.getAAirStatAccess().getChordKeyword_7());
    }
this_WS_8=RULE_WS
    { 
    newLeafNode(this_WS_8, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_8()); 
    }
	otherlv_9='NFoil' 
    {
    	newLeafNode(otherlv_9, grammarAccess.getAAirStatAccess().getNFoilKeyword_9());
    }
this_WS_10=RULE_WS
    { 
    newLeafNode(this_WS_10, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_10()); 
    }
	otherlv_11='PrnElm' 
    {
    	newLeafNode(otherlv_11, grammarAccess.getAAirStatAccess().getPrnElmKeyword_11());
    }
(this_WS_12=RULE_WS
    { 
    newLeafNode(this_WS_12, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_12()); 
    }
)?(this_SL_COMMENT_13=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_13, grammarAccess.getAAirStatAccess().getSL_COMMENTTerminalRuleCall_13()); 
    }
)?this_NEWLINE_14=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_14, grammarAccess.getAAirStatAccess().getNEWLINETerminalRuleCall_14()); 
    }
((this_WS_15=RULE_WS
    { 
    newLeafNode(this_WS_15, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_15_0()); 
    }
)?(
(
		{ 
	        newCompositeNode(grammarAccess.getAAirStatAccess().getRnodesTNUMBERParserRuleCall_15_1_0()); 
	    }
		lv_rnodes_16_0=ruletNUMBER		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getAAirStatRule());
	        }
       		add(
       			$current, 
       			"rnodes",
        		lv_rnodes_16_0, 
        		"tNUMBER");
	        afterParserOrEnumRuleCall();
	    }

)
)this_WS_17=RULE_WS
    { 
    newLeafNode(this_WS_17, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_15_2()); 
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getAAirStatAccess().getAerotwstTNUMBERParserRuleCall_15_3_0()); 
	    }
		lv_aerotwst_18_0=ruletNUMBER		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getAAirStatRule());
	        }
       		add(
       			$current, 
       			"aerotwst",
        		lv_aerotwst_18_0, 
        		"tNUMBER");
	        afterParserOrEnumRuleCall();
	    }

)
)this_WS_19=RULE_WS
    { 
    newLeafNode(this_WS_19, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_15_4()); 
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getAAirStatAccess().getDrnodesTNUMBERParserRuleCall_15_5_0()); 
	    }
		lv_drnodes_20_0=ruletNUMBER		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getAAirStatRule());
	        }
       		add(
       			$current, 
       			"drnodes",
        		lv_drnodes_20_0, 
        		"tNUMBER");
	        afterParserOrEnumRuleCall();
	    }

)
)this_WS_21=RULE_WS
    { 
    newLeafNode(this_WS_21, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_15_6()); 
    }
(
(
		{ 
	        newCompositeNode(grammarAccess.getAAirStatAccess().getChordTNUMBERParserRuleCall_15_7_0()); 
	    }
		lv_chord_22_0=ruletNUMBER		{
	        if ($current==null) {
	            $current = createModelElementForParent(grammarAccess.getAAirStatRule());
	        }
       		add(
       			$current, 
       			"chord",
        		lv_chord_22_0, 
        		"tNUMBER");
	        afterParserOrEnumRuleCall();
	    }

)
)this_WS_23=RULE_WS
    { 
    newLeafNode(this_WS_23, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_15_8()); 
    }
(
(
		lv_nfoil_24_0=RULE_INT
		{
			newLeafNode(lv_nfoil_24_0, grammarAccess.getAAirStatAccess().getNfoilINTTerminalRuleCall_15_9_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAAirStatRule());
	        }
       		addWithLastConsumed(
       			$current, 
       			"nfoil",
        		lv_nfoil_24_0, 
        		"INT");
	    }

)
)this_WS_25=RULE_WS
    { 
    newLeafNode(this_WS_25, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_15_10()); 
    }
(
(
		lv_prnelm_26_0=RULE_PRINT
		{
			newLeafNode(lv_prnelm_26_0, grammarAccess.getAAirStatAccess().getPrnelmPRINTTerminalRuleCall_15_11_0()); 
		}
		{
	        if ($current==null) {
	            $current = createModelElement(grammarAccess.getAAirStatRule());
	        }
       		addWithLastConsumed(
       			$current, 
       			"prnelm",
        		lv_prnelm_26_0, 
        		"PRINT");
	    }

)
)(this_WS_27=RULE_WS
    { 
    newLeafNode(this_WS_27, grammarAccess.getAAirStatAccess().getWSTerminalRuleCall_15_12()); 
    }
)?(this_SL_COMMENT_28=RULE_SL_COMMENT
    { 
    newLeafNode(this_SL_COMMENT_28, grammarAccess.getAAirStatAccess().getSL_COMMENTTerminalRuleCall_15_13()); 
    }
)?this_NEWLINE_29=RULE_NEWLINE
    { 
    newLeafNode(this_NEWLINE_29, grammarAccess.getAAirStatAccess().getNEWLINETerminalRuleCall_15_14()); 
    }
)+)
;
finally {
	myHiddenTokenState.restore();
}





RULE_INT : ('0'..'9')+;

RULE_NUMBER : (('+'|'-')? RULE_INT '.' RULE_INT? (('E'|'e') ('+'|'-')? RULE_INT)?|('+'|'-')? RULE_INT ('E'|'e') ('+'|'-')? RULE_INT|'.' RULE_INT (('E'|'e') ('+'|'-')? RULE_INT)?|'-' RULE_INT);

RULE_UNITS : 'SI';

RULE_STALL : ('BEDDOES'|'STEADY');

RULE_CM : ('USE_CM'|'NO_CM');

RULE_INFMODEL : ('EQUIL'|'DYNIN');

RULE_INDMODEL : ('NONE'|'WAKE'|'SWIRL');

RULE_PRANDTL : ('PRANDtl'|'NONE');

RULE_PRINT : ('PRINT'|'NOPRINT');

RULE_STRING : ('"' ('\\' ('b'|'t'|'n'|'f'|'r'|'u'|'"'|'\''|'\\')|~(('\\'|'"')))* '"'|'\'' ('\\' ('b'|'t'|'n'|'f'|'r'|'u'|'"'|'\''|'\\')|~(('\\'|'\'')))* '\'');

RULE_NEWLINE : ('\r'|'\n'|'\r\n');

RULE_SL_COMMENT : '-' ~('0'..'9') ~(('\r'|'\n'|'\r\n'))*;

RULE_WS : (' '|'\t')+;


