/*
* generated by Xtext
*/
package sc.ndt.editor.fast.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import sc.ndt.editor.fast.services.FasttwrGrammarAccess;

public class FasttwrParser extends AbstractContentAssistParser {
	
	@Inject
	private FasttwrGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected sc.ndt.editor.fast.ui.contentassist.antlr.internal.InternalFasttwrParser createParser() {
		sc.ndt.editor.fast.ui.contentassist.antlr.internal.InternalFasttwrParser result = new sc.ndt.editor.fast.ui.contentassist.antlr.internal.InternalFasttwrParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelFasttwrAccess().getAlternatives_40(), "rule__ModelFasttwr__Alternatives_40");
					put(grammarAccess.getTNUMBERAccess().getAlternatives(), "rule__TNUMBER__Alternatives");
					put(grammarAccess.getTBOOLAccess().getAlternatives(), "rule__TBOOL__Alternatives");
					put(grammarAccess.getModelFasttwrAccess().getGroup(), "rule__ModelFasttwr__Group__0");
					put(grammarAccess.getHeaderAccess().getGroup(), "rule__Header__Group__0");
					put(grammarAccess.getSectionAccess().getGroup(), "rule__Section__Group__0");
					put(grammarAccess.getNNTwInpStAccess().getGroup(), "rule__NNTwInpSt__Group__0");
					put(grammarAccess.getBCalcTModeAccess().getGroup(), "rule__BCalcTMode__Group__0");
					put(grammarAccess.getNTwrFADmp1Access().getGroup(), "rule__NTwrFADmp1__Group__0");
					put(grammarAccess.getNTwrFADmp2Access().getGroup(), "rule__NTwrFADmp2__Group__0");
					put(grammarAccess.getNTwrSSDmp1Access().getGroup(), "rule__NTwrSSDmp1__Group__0");
					put(grammarAccess.getNTwrSSDmp2Access().getGroup(), "rule__NTwrSSDmp2__Group__0");
					put(grammarAccess.getNFAStTunr1Access().getGroup(), "rule__NFAStTunr1__Group__0");
					put(grammarAccess.getNFAStTunr2Access().getGroup(), "rule__NFAStTunr2__Group__0");
					put(grammarAccess.getNSSStTunr1Access().getGroup(), "rule__NSSStTunr1__Group__0");
					put(grammarAccess.getNSSStTunr2Access().getGroup(), "rule__NSSStTunr2__Group__0");
					put(grammarAccess.getAdjTwMaAccess().getGroup(), "rule__AdjTwMa__Group__0");
					put(grammarAccess.getAdjFAStAccess().getGroup(), "rule__AdjFASt__Group__0");
					put(grammarAccess.getAdjSSStAccess().getGroup(), "rule__AdjSSSt__Group__0");
					put(grammarAccess.getNTwFAM1Sh2Access().getGroup(), "rule__NTwFAM1Sh2__Group__0");
					put(grammarAccess.getNTwFAM1Sh3Access().getGroup(), "rule__NTwFAM1Sh3__Group__0");
					put(grammarAccess.getNTwFAM1Sh4Access().getGroup(), "rule__NTwFAM1Sh4__Group__0");
					put(grammarAccess.getNTwFAM1Sh5Access().getGroup(), "rule__NTwFAM1Sh5__Group__0");
					put(grammarAccess.getNTwFAM1Sh6Access().getGroup(), "rule__NTwFAM1Sh6__Group__0");
					put(grammarAccess.getNTwFAM2Sh2Access().getGroup(), "rule__NTwFAM2Sh2__Group__0");
					put(grammarAccess.getNTwFAM2Sh3Access().getGroup(), "rule__NTwFAM2Sh3__Group__0");
					put(grammarAccess.getNTwFAM2Sh4Access().getGroup(), "rule__NTwFAM2Sh4__Group__0");
					put(grammarAccess.getNTwFAM2Sh5Access().getGroup(), "rule__NTwFAM2Sh5__Group__0");
					put(grammarAccess.getNTwFAM2Sh6Access().getGroup(), "rule__NTwFAM2Sh6__Group__0");
					put(grammarAccess.getNTwSSM1Sh2Access().getGroup(), "rule__NTwSSM1Sh2__Group__0");
					put(grammarAccess.getNTwSSM1Sh3Access().getGroup(), "rule__NTwSSM1Sh3__Group__0");
					put(grammarAccess.getNTwSSM1Sh4Access().getGroup(), "rule__NTwSSM1Sh4__Group__0");
					put(grammarAccess.getNTwSSM1Sh5Access().getGroup(), "rule__NTwSSM1Sh5__Group__0");
					put(grammarAccess.getNTwSSM1Sh6Access().getGroup(), "rule__NTwSSM1Sh6__Group__0");
					put(grammarAccess.getNTwSSM2Sh2Access().getGroup(), "rule__NTwSSM2Sh2__Group__0");
					put(grammarAccess.getNTwSSM2Sh3Access().getGroup(), "rule__NTwSSM2Sh3__Group__0");
					put(grammarAccess.getNTwSSM2Sh4Access().getGroup(), "rule__NTwSSM2Sh4__Group__0");
					put(grammarAccess.getNTwSSM2Sh5Access().getGroup(), "rule__NTwSSM2Sh5__Group__0");
					put(grammarAccess.getNTwSSM2Sh6Access().getGroup(), "rule__NTwSSM2Sh6__Group__0");
					put(grammarAccess.getATwrStatAccess().getGroup(), "rule__ATwrStat__Group__0");
					put(grammarAccess.getATwrStatAccess().getGroup_46(), "rule__ATwrStat__Group_46__0");
					put(grammarAccess.getModelFasttwrAccess().getHeadAssignment_0(), "rule__ModelFasttwr__HeadAssignment_0");
					put(grammarAccess.getModelFasttwrAccess().getSectionsAssignment_1(), "rule__ModelFasttwr__SectionsAssignment_1");
					put(grammarAccess.getModelFasttwrAccess().getNTwInpStAssignment_2(), "rule__ModelFasttwr__NTwInpStAssignment_2");
					put(grammarAccess.getModelFasttwrAccess().getCalcTModeAssignment_3(), "rule__ModelFasttwr__CalcTModeAssignment_3");
					put(grammarAccess.getModelFasttwrAccess().getBldFlDmp1Assignment_4(), "rule__ModelFasttwr__BldFlDmp1Assignment_4");
					put(grammarAccess.getModelFasttwrAccess().getBldFlDmp2Assignment_5(), "rule__ModelFasttwr__BldFlDmp2Assignment_5");
					put(grammarAccess.getModelFasttwrAccess().getBldEdDmp1Assignment_6(), "rule__ModelFasttwr__BldEdDmp1Assignment_6");
					put(grammarAccess.getModelFasttwrAccess().getBldEdDmp2Assignment_7(), "rule__ModelFasttwr__BldEdDmp2Assignment_7");
					put(grammarAccess.getModelFasttwrAccess().getSectionsAssignment_8(), "rule__ModelFasttwr__SectionsAssignment_8");
					put(grammarAccess.getModelFasttwrAccess().getFAStTunr1Assignment_9(), "rule__ModelFasttwr__FAStTunr1Assignment_9");
					put(grammarAccess.getModelFasttwrAccess().getFAStTunr2Assignment_10(), "rule__ModelFasttwr__FAStTunr2Assignment_10");
					put(grammarAccess.getModelFasttwrAccess().getSSStTunr1Assignment_11(), "rule__ModelFasttwr__SSStTunr1Assignment_11");
					put(grammarAccess.getModelFasttwrAccess().getSSStTunr2Assignment_12(), "rule__ModelFasttwr__SSStTunr2Assignment_12");
					put(grammarAccess.getModelFasttwrAccess().getAdjTwMaAssignment_13(), "rule__ModelFasttwr__AdjTwMaAssignment_13");
					put(grammarAccess.getModelFasttwrAccess().getAdjFAStAssignment_14(), "rule__ModelFasttwr__AdjFAStAssignment_14");
					put(grammarAccess.getModelFasttwrAccess().getAdjSSStAssignment_15(), "rule__ModelFasttwr__AdjSSStAssignment_15");
					put(grammarAccess.getModelFasttwrAccess().getSectionsAssignment_16(), "rule__ModelFasttwr__SectionsAssignment_16");
					put(grammarAccess.getModelFasttwrAccess().getTwrStatAssignment_17(), "rule__ModelFasttwr__TwrStatAssignment_17");
					put(grammarAccess.getModelFasttwrAccess().getSectionsAssignment_18(), "rule__ModelFasttwr__SectionsAssignment_18");
					put(grammarAccess.getModelFasttwrAccess().getTwFAM1Sh2Assignment_19(), "rule__ModelFasttwr__TwFAM1Sh2Assignment_19");
					put(grammarAccess.getModelFasttwrAccess().getTwFAM1Sh3Assignment_20(), "rule__ModelFasttwr__TwFAM1Sh3Assignment_20");
					put(grammarAccess.getModelFasttwrAccess().getTwFAM1Sh4Assignment_21(), "rule__ModelFasttwr__TwFAM1Sh4Assignment_21");
					put(grammarAccess.getModelFasttwrAccess().getTwFAM1Sh5Assignment_22(), "rule__ModelFasttwr__TwFAM1Sh5Assignment_22");
					put(grammarAccess.getModelFasttwrAccess().getTwFAM1Sh6Assignment_23(), "rule__ModelFasttwr__TwFAM1Sh6Assignment_23");
					put(grammarAccess.getModelFasttwrAccess().getTwFAM2Sh2Assignment_24(), "rule__ModelFasttwr__TwFAM2Sh2Assignment_24");
					put(grammarAccess.getModelFasttwrAccess().getTwFAM2Sh3Assignment_25(), "rule__ModelFasttwr__TwFAM2Sh3Assignment_25");
					put(grammarAccess.getModelFasttwrAccess().getTwFAM2Sh4Assignment_26(), "rule__ModelFasttwr__TwFAM2Sh4Assignment_26");
					put(grammarAccess.getModelFasttwrAccess().getTwFAM2Sh5Assignment_27(), "rule__ModelFasttwr__TwFAM2Sh5Assignment_27");
					put(grammarAccess.getModelFasttwrAccess().getTwFAM2Sh6Assignment_28(), "rule__ModelFasttwr__TwFAM2Sh6Assignment_28");
					put(grammarAccess.getModelFasttwrAccess().getSectionsAssignment_29(), "rule__ModelFasttwr__SectionsAssignment_29");
					put(grammarAccess.getModelFasttwrAccess().getTwSSM1Sh2Assignment_30(), "rule__ModelFasttwr__TwSSM1Sh2Assignment_30");
					put(grammarAccess.getModelFasttwrAccess().getTwSSM1Sh3Assignment_31(), "rule__ModelFasttwr__TwSSM1Sh3Assignment_31");
					put(grammarAccess.getModelFasttwrAccess().getTwSSM1Sh4Assignment_32(), "rule__ModelFasttwr__TwSSM1Sh4Assignment_32");
					put(grammarAccess.getModelFasttwrAccess().getTwSSM1Sh5Assignment_33(), "rule__ModelFasttwr__TwSSM1Sh5Assignment_33");
					put(grammarAccess.getModelFasttwrAccess().getTwSSM1Sh6Assignment_34(), "rule__ModelFasttwr__TwSSM1Sh6Assignment_34");
					put(grammarAccess.getModelFasttwrAccess().getTwSSM2Sh2Assignment_35(), "rule__ModelFasttwr__TwSSM2Sh2Assignment_35");
					put(grammarAccess.getModelFasttwrAccess().getTwSSM2Sh3Assignment_36(), "rule__ModelFasttwr__TwSSM2Sh3Assignment_36");
					put(grammarAccess.getModelFasttwrAccess().getTwSSM2Sh4Assignment_37(), "rule__ModelFasttwr__TwSSM2Sh4Assignment_37");
					put(grammarAccess.getModelFasttwrAccess().getTwSSM2Sh5Assignment_38(), "rule__ModelFasttwr__TwSSM2Sh5Assignment_38");
					put(grammarAccess.getModelFasttwrAccess().getTwSSM2Sh6Assignment_39(), "rule__ModelFasttwr__TwSSM2Sh6Assignment_39");
					put(grammarAccess.getHeaderAccess().getNameAssignment_4(), "rule__Header__NameAssignment_4");
					put(grammarAccess.getSectionAccess().getNameAssignment_0(), "rule__Section__NameAssignment_0");
					put(grammarAccess.getNNTwInpStAccess().getValueAssignment_1(), "rule__NNTwInpSt__ValueAssignment_1");
					put(grammarAccess.getNNTwInpStAccess().getNameAssignment_3(), "rule__NNTwInpSt__NameAssignment_3");
					put(grammarAccess.getBCalcTModeAccess().getValueAssignment_1(), "rule__BCalcTMode__ValueAssignment_1");
					put(grammarAccess.getBCalcTModeAccess().getNameAssignment_3(), "rule__BCalcTMode__NameAssignment_3");
					put(grammarAccess.getNTwrFADmp1Access().getValueAssignment_1(), "rule__NTwrFADmp1__ValueAssignment_1");
					put(grammarAccess.getNTwrFADmp1Access().getNameAssignment_3(), "rule__NTwrFADmp1__NameAssignment_3");
					put(grammarAccess.getNTwrFADmp2Access().getValueAssignment_1(), "rule__NTwrFADmp2__ValueAssignment_1");
					put(grammarAccess.getNTwrFADmp2Access().getNameAssignment_3(), "rule__NTwrFADmp2__NameAssignment_3");
					put(grammarAccess.getNTwrSSDmp1Access().getValueAssignment_1(), "rule__NTwrSSDmp1__ValueAssignment_1");
					put(grammarAccess.getNTwrSSDmp1Access().getNameAssignment_3(), "rule__NTwrSSDmp1__NameAssignment_3");
					put(grammarAccess.getNTwrSSDmp2Access().getValueAssignment_1(), "rule__NTwrSSDmp2__ValueAssignment_1");
					put(grammarAccess.getNTwrSSDmp2Access().getNameAssignment_3(), "rule__NTwrSSDmp2__NameAssignment_3");
					put(grammarAccess.getNFAStTunr1Access().getValueAssignment_1(), "rule__NFAStTunr1__ValueAssignment_1");
					put(grammarAccess.getNFAStTunr1Access().getNameAssignment_3(), "rule__NFAStTunr1__NameAssignment_3");
					put(grammarAccess.getNFAStTunr2Access().getValueAssignment_1(), "rule__NFAStTunr2__ValueAssignment_1");
					put(grammarAccess.getNFAStTunr2Access().getNameAssignment_3(), "rule__NFAStTunr2__NameAssignment_3");
					put(grammarAccess.getNSSStTunr1Access().getValueAssignment_1(), "rule__NSSStTunr1__ValueAssignment_1");
					put(grammarAccess.getNSSStTunr1Access().getNameAssignment_3(), "rule__NSSStTunr1__NameAssignment_3");
					put(grammarAccess.getNSSStTunr2Access().getValueAssignment_1(), "rule__NSSStTunr2__ValueAssignment_1");
					put(grammarAccess.getNSSStTunr2Access().getNameAssignment_3(), "rule__NSSStTunr2__NameAssignment_3");
					put(grammarAccess.getAdjTwMaAccess().getValueAssignment_1(), "rule__AdjTwMa__ValueAssignment_1");
					put(grammarAccess.getAdjTwMaAccess().getNameAssignment_3(), "rule__AdjTwMa__NameAssignment_3");
					put(grammarAccess.getAdjFAStAccess().getValueAssignment_1(), "rule__AdjFASt__ValueAssignment_1");
					put(grammarAccess.getAdjFAStAccess().getNameAssignment_3(), "rule__AdjFASt__NameAssignment_3");
					put(grammarAccess.getAdjSSStAccess().getValueAssignment_1(), "rule__AdjSSSt__ValueAssignment_1");
					put(grammarAccess.getAdjSSStAccess().getNameAssignment_3(), "rule__AdjSSSt__NameAssignment_3");
					put(grammarAccess.getNTwFAM1Sh2Access().getValueAssignment_1(), "rule__NTwFAM1Sh2__ValueAssignment_1");
					put(grammarAccess.getNTwFAM1Sh2Access().getNameAssignment_3(), "rule__NTwFAM1Sh2__NameAssignment_3");
					put(grammarAccess.getNTwFAM1Sh3Access().getValueAssignment_1(), "rule__NTwFAM1Sh3__ValueAssignment_1");
					put(grammarAccess.getNTwFAM1Sh3Access().getNameAssignment_3(), "rule__NTwFAM1Sh3__NameAssignment_3");
					put(grammarAccess.getNTwFAM1Sh4Access().getValueAssignment_1(), "rule__NTwFAM1Sh4__ValueAssignment_1");
					put(grammarAccess.getNTwFAM1Sh4Access().getNameAssignment_3(), "rule__NTwFAM1Sh4__NameAssignment_3");
					put(grammarAccess.getNTwFAM1Sh5Access().getValueAssignment_1(), "rule__NTwFAM1Sh5__ValueAssignment_1");
					put(grammarAccess.getNTwFAM1Sh5Access().getNameAssignment_3(), "rule__NTwFAM1Sh5__NameAssignment_3");
					put(grammarAccess.getNTwFAM1Sh6Access().getValueAssignment_1(), "rule__NTwFAM1Sh6__ValueAssignment_1");
					put(grammarAccess.getNTwFAM1Sh6Access().getNameAssignment_3(), "rule__NTwFAM1Sh6__NameAssignment_3");
					put(grammarAccess.getNTwFAM2Sh2Access().getValueAssignment_1(), "rule__NTwFAM2Sh2__ValueAssignment_1");
					put(grammarAccess.getNTwFAM2Sh2Access().getNameAssignment_3(), "rule__NTwFAM2Sh2__NameAssignment_3");
					put(grammarAccess.getNTwFAM2Sh3Access().getValueAssignment_1(), "rule__NTwFAM2Sh3__ValueAssignment_1");
					put(grammarAccess.getNTwFAM2Sh3Access().getNameAssignment_3(), "rule__NTwFAM2Sh3__NameAssignment_3");
					put(grammarAccess.getNTwFAM2Sh4Access().getValueAssignment_1(), "rule__NTwFAM2Sh4__ValueAssignment_1");
					put(grammarAccess.getNTwFAM2Sh4Access().getNameAssignment_3(), "rule__NTwFAM2Sh4__NameAssignment_3");
					put(grammarAccess.getNTwFAM2Sh5Access().getValueAssignment_1(), "rule__NTwFAM2Sh5__ValueAssignment_1");
					put(grammarAccess.getNTwFAM2Sh5Access().getNameAssignment_3(), "rule__NTwFAM2Sh5__NameAssignment_3");
					put(grammarAccess.getNTwFAM2Sh6Access().getValueAssignment_1(), "rule__NTwFAM2Sh6__ValueAssignment_1");
					put(grammarAccess.getNTwFAM2Sh6Access().getNameAssignment_3(), "rule__NTwFAM2Sh6__NameAssignment_3");
					put(grammarAccess.getNTwSSM1Sh2Access().getValueAssignment_1(), "rule__NTwSSM1Sh2__ValueAssignment_1");
					put(grammarAccess.getNTwSSM1Sh2Access().getNameAssignment_3(), "rule__NTwSSM1Sh2__NameAssignment_3");
					put(grammarAccess.getNTwSSM1Sh3Access().getValueAssignment_1(), "rule__NTwSSM1Sh3__ValueAssignment_1");
					put(grammarAccess.getNTwSSM1Sh3Access().getNameAssignment_3(), "rule__NTwSSM1Sh3__NameAssignment_3");
					put(grammarAccess.getNTwSSM1Sh4Access().getValueAssignment_1(), "rule__NTwSSM1Sh4__ValueAssignment_1");
					put(grammarAccess.getNTwSSM1Sh4Access().getNameAssignment_3(), "rule__NTwSSM1Sh4__NameAssignment_3");
					put(grammarAccess.getNTwSSM1Sh5Access().getValueAssignment_1(), "rule__NTwSSM1Sh5__ValueAssignment_1");
					put(grammarAccess.getNTwSSM1Sh5Access().getNameAssignment_3(), "rule__NTwSSM1Sh5__NameAssignment_3");
					put(grammarAccess.getNTwSSM1Sh6Access().getValueAssignment_1(), "rule__NTwSSM1Sh6__ValueAssignment_1");
					put(grammarAccess.getNTwSSM1Sh6Access().getNameAssignment_3(), "rule__NTwSSM1Sh6__NameAssignment_3");
					put(grammarAccess.getNTwSSM2Sh2Access().getValueAssignment_1(), "rule__NTwSSM2Sh2__ValueAssignment_1");
					put(grammarAccess.getNTwSSM2Sh2Access().getNameAssignment_3(), "rule__NTwSSM2Sh2__NameAssignment_3");
					put(grammarAccess.getNTwSSM2Sh3Access().getValueAssignment_1(), "rule__NTwSSM2Sh3__ValueAssignment_1");
					put(grammarAccess.getNTwSSM2Sh3Access().getNameAssignment_3(), "rule__NTwSSM2Sh3__NameAssignment_3");
					put(grammarAccess.getNTwSSM2Sh4Access().getValueAssignment_1(), "rule__NTwSSM2Sh4__ValueAssignment_1");
					put(grammarAccess.getNTwSSM2Sh4Access().getNameAssignment_3(), "rule__NTwSSM2Sh4__NameAssignment_3");
					put(grammarAccess.getNTwSSM2Sh5Access().getValueAssignment_1(), "rule__NTwSSM2Sh5__ValueAssignment_1");
					put(grammarAccess.getNTwSSM2Sh5Access().getNameAssignment_3(), "rule__NTwSSM2Sh5__NameAssignment_3");
					put(grammarAccess.getNTwSSM2Sh6Access().getValueAssignment_1(), "rule__NTwSSM2Sh6__ValueAssignment_1");
					put(grammarAccess.getNTwSSM2Sh6Access().getNameAssignment_3(), "rule__NTwSSM2Sh6__NameAssignment_3");
					put(grammarAccess.getATwrStatAccess().getHtFractAssignment_46_1(), "rule__ATwrStat__HtFractAssignment_46_1");
					put(grammarAccess.getATwrStatAccess().getTMassDenAssignment_46_3(), "rule__ATwrStat__TMassDenAssignment_46_3");
					put(grammarAccess.getATwrStatAccess().getTwFAStifAssignment_46_5(), "rule__ATwrStat__TwFAStifAssignment_46_5");
					put(grammarAccess.getATwrStatAccess().getTwSSStifAssignment_46_7(), "rule__ATwrStat__TwSSStifAssignment_46_7");
					put(grammarAccess.getATwrStatAccess().getTwGJStifAssignment_46_9(), "rule__ATwrStat__TwGJStifAssignment_46_9");
					put(grammarAccess.getATwrStatAccess().getTwEAStifAssignment_46_11(), "rule__ATwrStat__TwEAStifAssignment_46_11");
					put(grammarAccess.getATwrStatAccess().getTwFAInerAssignment_46_13(), "rule__ATwrStat__TwFAInerAssignment_46_13");
					put(grammarAccess.getATwrStatAccess().getTwSSInerAssignment_46_15(), "rule__ATwrStat__TwSSInerAssignment_46_15");
					put(grammarAccess.getATwrStatAccess().getTwFAcgOfAssignment_46_17(), "rule__ATwrStat__TwFAcgOfAssignment_46_17");
					put(grammarAccess.getATwrStatAccess().getTwSScgOfAssignment_46_19(), "rule__ATwrStat__TwSScgOfAssignment_46_19");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			sc.ndt.editor.fast.ui.contentassist.antlr.internal.InternalFasttwrParser typedParser = (sc.ndt.editor.fast.ui.contentassist.antlr.internal.InternalFasttwrParser) parser;
			typedParser.entryRuleModelFasttwr();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] {  };
	}
	
	public FasttwrGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FasttwrGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
