/**
 * generated by Xtext
 */
package sc.ndt.editor.bmodes.ui.contentassist;

import sc.ndt.editor.bmodes.ui.contentassist.AbstractBmodestspProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class BmodestspProposalProvider extends AbstractBmodestspProposalProvider {
}
